#!/bin/sh

# Copyright (C) 2015 Hans-Peter Jansen
# Copyright (C) 1998, 2002, 2004 Free Software Foundation
# Copyright (C) 1993 Jean-loup Gailly

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


PATH="/usr/bin:$PATH"; export PATH
check=0
pipe=0
opt=
files=
keep=0
res=0
old=0
new=0
block=1024
# block is the disk block size (best guess, need not be exact)

warn="(does not preserve modes and timestamp)"
tmp=`mktemp -d ${TMPDIR-/tmp}/zfoo.XXXXXX` || {
       echo 'cannot create temporary directory' >&2
       exit 1
}
trap "rm -rf $tmp/" 0 1 2 3 6 13 15
set -C
echo hi > $tmp/1
echo hi > $tmp/2
if test -z "`(${CPMOD-cpmod} $tmp/1 $tmp/2) 2>&1`"; then
  cpmod=${CPMOD-cpmod}
  warn=""
fi

if test -z "$cpmod" && ${TOUCH-touch} -r $tmp/1 $tmp/2 2>/dev/null; then
  cpmod="${TOUCH-touch}"
  cpmodarg="-r"
  warn="(does not preserve file modes)"
fi

# check about xz extension
xz $tmp/1 &> /dev/null
ext=`echo $tmp/1* | sed "s|$tmp/1||"`
rm -rf $tmp/
trap - 0 1 2 3 6 13 15
if test -z "$ext"; then
  echo xznew: error determining xz extension
  exit 1
fi
if test "$ext" = ".gz"; then
  echo xznew: cannot use .gz as xz extension.
  exit 1
fi

for arg
do
  case "$arg" in
  -*)     opt="$opt $arg"; shift;;
   *)     break;;
  esac
done

if test $# -eq 0; then
  echo "recompress .gz or .tgz files into $ext (xz) files"
  echo usage: `echo $0 | sed 's,^.*/,,'` "[-tv9KP]" file.gz...
  echo "  -t tests the new files before deleting originals"
  echo "  -v be verbose"
  echo "  -9 use the slowest compression method (optimal compression)"
  echo "  -K keep a .gz file when it is smaller than the $ext file"
  echo "  -P use pipes for the conversion $warn"
  exit 1
fi

opt=`echo "$opt" | sed -e 's/ //g' -e 's/-//g'`
case "$opt" in
  *t*) check=1; opt=`echo "$opt" | sed 's/t//g'`
esac
case "$opt" in
  *K*) keep=1; opt=`echo "$opt" | sed 's/K//g'`
esac
case "$opt" in
  *P*) pipe=1; opt=`echo "$opt" | sed 's/P//g'`
esac
if test -n "$opt"; then
  opt="-$opt"
fi

for i do
  m=`echo $i | sed 's/\.tgz$//'`
  if test -f "$m.tgz" ; then
   echo "Renaming file *.tgz to *.tar.gz"
   mv "$i" "$m.tar.gz"
   n=`echo $i | sed 's/\.tgz$/\.tar/'`
  else 
   n=`echo $i | sed 's/\.gz$//'`
  fi
  if test ! -f "$n.gz" ; then
    echo $n.gz not found
    res=1; continue
  fi
  test $keep -eq 1 && old=`wc -c < "$n.gz"`
  if test $pipe -eq 1; then
    if gzip -d < "$n.gz" | xz $opt > "$n$ext"; then
      # Copy file attributes from old file to new one, if possible.
      test -n "$cpmod" && $cpmod $cpmodarg "$n.gz" "$n$ext" 2> /dev/null
    else
      echo error while recompressing $n.gz
      res=1; continue
    fi
  else
    if test $check -eq 1; then
      if cp -p "$n.gz" "$n.$$" 2> /dev/null || cp "$n.gz" "$n.$$"; then
	:
      else
	echo cannot backup "$n.gz"
        res=1; continue
      fi
    fi
    if gzip -d "$n.gz"; then
      :
    else
      test $check -eq 1 && mv "$n.$$" "$n.gz"
      echo error while uncompressing $n.gz
      res=1; continue
    fi
    if xz $opt "$n"; then
      :
    else
      if test $check -eq 1; then
	mv "$n.$$" "$n.gz" && rm -f "$n"
        echo error while recompressing $n
      else
	# gzip $n  (might be dangerous if disk full)
        echo error while recompressing $n, left uncompressed
      fi
      res=1; continue
    fi
  fi
  test $keep -eq 1 && new=`wc -c < "$n$ext"`
  if test $keep -eq 1 && test `expr \( $old + $block - 1 \) / $block` -lt \
			      `expr \( $new + $block - 1 \) / $block`; then
    if test $pipe -eq 1; then
      rm -f "$n$ext"
    elif test $check -eq 1; then
      mv "$n.$$" "$n.gz" && rm -f "$n$ext"
    else
      xz -d "$n$ext" && gzip "$n" && rm -f "$n$ext"
    fi
    echo "$n.gz smaller than $n$ext -- unchanged"

  elif test $check -eq 1; then
    if xz -t "$n$ext" ; then
      rm -f "$n.$$" "$n.gz"
    else
      test $pipe -eq 0 && mv "$n.$$" "$n.gz"
      rm -f "$n$ext"
      echo error while testing $n$ext, $n.gz unchanged
      res=1; continue
    fi
  elif test $pipe -eq 1; then
    rm -f "$n.gz"
  fi
done
exit $res
