# SUSE: We don't ship CNI in older SLE/ALP streams.
# Override the default CNI plugin search paths.
# bsc#1213556 (https://github.com/containers/podman/issues/19327)
[network]
cni_plugin_dirs = ["@LIBEXECDIR@/cni"]
