# tmpfiles.d(5) lock directory for ckermit
#Type Path                            Mode UID           GID          Age Argument
    d /run/lock/uucp                  0771 root          dialout      -   -
