.TH "dunelegacy" "6" "0.96.4" "Dmitriy A. Perlow aka DAP-DarkneSS" ""
.SH "NAME"
A modern Dune II reimplementation.
.br
.SH "SYNTAX"
dunelegacy [--showlog] [--fullscreen|--window] [--PlayerName=X] [--ServerPort=X]
.br
.SH "DESCRIPTION"
Lead one of three interplanetary houses, Atreides, Harkonnen or Ordos, in an attempt to harvest the largest amount of spice from the sand dunes. Exchange your spice stockpiles for credits through refinement and build an army capable of thwarting attempts of the other houses to stop your harvesting!
.br

Dune Legacy is an effort by a handful of developers to revitalize the first-ever real-time strategy game. The original game was the basis for the hugely successful Command and Conquer series, and the gameplay has been replicated an extended to a wide variety of storylines and series.
.br

NOTE: Original Dune 2 game files are needed.
.br
.SH "SEE ALSO"
IRC: #dunelegacy @ irc.freenode.net
.br
Web: http://sourceforge.net/projects/dunelegacy
.br
