#
# spec file for package gap-automgrp
#
# Copyright (c) 2022 SUSE LLC
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Please submit bugfixes or comments via https://bugs.opensuse.org/
#


Name:           gap-automgrp
Version:        1.3.2
Release:        0
Summary:        GAP: Automata groups
License:        MIT
Group:          Productivity/Scientific/Math
URL:            https://gap-packages.github.io/automgrp/

Source:         https://github.com/gap-packages/automgrp/releases/download/v%version/automgrp-%version.tar.gz
BuildRequires:  gap-rpm-devel
BuildArch:      noarch
Requires:       gap-core >= 4.9.1
Requires:       gap-fga >= 1.1.0.1
Suggests:       gap-fr >= 2.0.0

%description
The AutomGrp package provides methods for computations with groups
and semigroups generated by finite automata or given by wreath
recursions, as well as with their finitely generated subgroups,
subsemigroups and elements.

%prep
%setup -qn automgrp-%version

%build

%install
%gappkg_simple_install

%files -f %name.files

%changelog
