.TH FUSION\-ICON "1" "11 December 2007"
.SH NAME
fusion\-icon \- tray icon to launch and manage Compiz Fusion
.SH SYNOPSIS
.B fusion\-icon\fR [\fBOPTIONS\fR]
.SH DESCRIPTION
.PP 
This manual page documents briefly the \fBfusion\-icon\fR command.
\fBfusion\-icon\fR is a tray icon for easy window manager and window
decorator switching, and it is being developed as part of the Open
Compositing project.
.SH OPTIONS
.TP
.B \-\-version
Show \fBfusion\-icon\fR's version number and exit.
.TP
\fB\-s\fR <seconds>, \fB\-\-sleep\fR=<seconds>
Sleep for \fIseconds\fR seconds before launching \fBfusion\-icon\fR.
.TP
\fB\-i\fR <interface>, \fB\-\-interface\fR=<interface>
Try a certain interface first.
.TP
\fB\-u\fR, \fB\-\-no\-interface\fR
Do not use any interface.
.TP
\fB\-f\fR, \fB\-\-force\-compiz\fR
Start compiz regardless of environment or configuration.
.TP
\fB\-n\fR, \fB\-\-no\-start\fR
Run, but do not start a window manager.

.SH SEE ALSO
.BR compiz (1)
.PP

.SH COPYRIGHT
\fBfusion\-icon\fR was written by Christopher Williams
<christopherw@verizon.net> and this manual page by Siegfried\-A. Gevatter
<rainct@ubuntu.com>.
.PP
Both are released under the GNU General Public License, version 2 or later.
