#
# spec file for package perl-Prima
#
# Copyright (c) 2025 SUSE LLC and contributors
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Please submit bugfixes or comments via https://bugs.opensuse.org/
#


%define cpan_name Prima
Name:           perl-Prima
Version:        1.77000
Release:        0
%define cpan_version 1.77
#Upstream: SUSE-Public-Domain
License:        AGPL-3.0-only AND BSD-2-Clause
Summary:        Perl graphic toolkit
URL:            https://metacpan.org/release/%{cpan_name}
Source0:        https://cpan.metacpan.org/authors/id/K/KA/KARASIK/%{cpan_name}-%{cpan_version}.tar.gz
Source1:        cpanspec.yml
Source100:      README.md
BuildRequires:  perl
BuildRequires:  perl-macros
Provides:       perl(Prima) = %{version}
Provides:       perl(Prima::AbstractButton)
Provides:       perl(Prima::AbstractDocker::Interface)
Provides:       perl(Prima::AbstractGrid)
Provides:       perl(Prima::AbstractGridViewer)
Provides:       perl(Prima::AbstractListBox)
Provides:       perl(Prima::AbstractListViewer)
Provides:       perl(Prima::AbstractMenu)
Provides:       perl(Prima::AbstractSlider)
Provides:       perl(Prima::AbstractSpinButton)
Provides:       perl(Prima::AccelTable)
Provides:       perl(Prima::AltSpinButton)
Provides:       perl(Prima::Application)
Provides:       perl(Prima::Button)
Provides:       perl(Prima::Buttons)
Provides:       perl(Prima::Calendar)
Provides:       perl(Prima::CheckBox)
Provides:       perl(Prima::CheckList)
Provides:       perl(Prima::CircularSlider)
Provides:       perl(Prima::Classes)
Provides:       perl(Prima::ClientWidgetDocker)
Provides:       perl(Prima::Clipboard)
Provides:       perl(Prima::Cluster)
Provides:       perl(Prima::ColorComboBox)
Provides:       perl(Prima::ComboBox)
Provides:       perl(Prima::ComboBox::Button)
Provides:       perl(Prima::Component)
Provides:       perl(Prima::Config)
Provides:       perl(Prima::Const)
Provides:       perl(Prima::CustomPodView)
Provides:       perl(Prima::DetailedList)
Provides:       perl(Prima::DetailedOutline)
Provides:       perl(Prima::DeviceBitmap)
Provides:       perl(Prima::Dialog)
Provides:       perl(Prima::Dialog::ChDirDialog)
Provides:       perl(Prima::Dialog::ColorDialog)
Provides:       perl(Prima::Dialog::FileDialog)
Provides:       perl(Prima::Dialog::FindDialog)
Provides:       perl(Prima::Dialog::FontDialog)
Provides:       perl(Prima::Dialog::ImageDialog)
Provides:       perl(Prima::Dialog::ImageOpenDialog)
Provides:       perl(Prima::Dialog::ImageSaveDialog)
Provides:       perl(Prima::Dialog::OpenDialog)
Provides:       perl(Prima::Dialog::PrintDialog)
Provides:       perl(Prima::Dialog::ReplaceDialog)
Provides:       perl(Prima::Dialog::SaveDialog)
Provides:       perl(Prima::DirectoryListBox)
Provides:       perl(Prima::DirectoryOutline)
Provides:       perl(Prima::DockManager)
Provides:       perl(Prima::DockManager::LaunchPad)
Provides:       perl(Prima::DockManager::Panelbar)
Provides:       perl(Prima::DockManager::S::SpeedButton)
Provides:       perl(Prima::DockManager::Toolbar)
Provides:       perl(Prima::DockManager::ToolbarDocker)
Provides:       perl(Prima::Docks)
Provides:       perl(Prima::Drawable)
Provides:       perl(Prima::Drawable::Antialias)
Provides:       perl(Prima::Drawable::Basic)
Provides:       perl(Prima::Drawable::CurvedText)
Provides:       perl(Prima::Drawable::Glyphs)
Provides:       perl(Prima::Drawable::Gradient)
Provides:       perl(Prima::Drawable::Markup)
Provides:       perl(Prima::Drawable::Metafile)
Provides:       perl(Prima::Drawable::Path)
Provides:       perl(Prima::Drawable::Pod)
Provides:       perl(Prima::Drawable::PolyTextBlock)
Provides:       perl(Prima::Drawable::Subcanvas)
Provides:       perl(Prima::Drawable::TextBlock)
Provides:       perl(Prima::DriveComboBox)
Provides:       perl(Prima::DriveComboBox::InputLine)
Provides:       perl(Prima::Edit)
Provides:       perl(Prima::EventHook)
Provides:       perl(Prima::ExtLists)
Provides:       perl(Prima::ExternalDockerShuttle)
Provides:       perl(Prima::File)
Provides:       perl(Prima::Font)
Provides:       perl(Prima::Font::Mapper)
Provides:       perl(Prima::FourPartDocker)
Provides:       perl(Prima::FrameSet)
Provides:       perl(Prima::FrameSet::Frame)
Provides:       perl(Prima::FrameSet::Slider)
Provides:       perl(Prima::Gauge)
Provides:       perl(Prima::Grid)
Provides:       perl(Prima::GridViewer)
Provides:       perl(Prima::Grids)
Provides:       perl(Prima::GroupBox)
Provides:       perl(Prima::HelpViewer)
Provides:       perl(Prima::HintWidget)
Provides:       perl(Prima::Icon)
Provides:       perl(Prima::Image)
Provides:       perl(Prima::Image::Animate)
Provides:       perl(Prima::Image::Animate::GIF)
Provides:       perl(Prima::Image::Animate::JXL)
Provides:       perl(Prima::Image::Animate::PNG)
Provides:       perl(Prima::Image::Animate::WebP)
Provides:       perl(Prima::Image::Animate::WebPNG)
Provides:       perl(Prima::Image::BasicTransparencyDialog)
Provides:       perl(Prima::Image::Exif)
Provides:       perl(Prima::Image::Loader)
Provides:       perl(Prima::Image::Saver)
Provides:       perl(Prima::Image::TransparencyControl)
Provides:       perl(Prima::Image::base64)
Provides:       perl(Prima::Image::gif)
Provides:       perl(Prima::Image::heif)
Provides:       perl(Prima::Image::jpeg)
Provides:       perl(Prima::Image::jxl)
Provides:       perl(Prima::Image::png)
Provides:       perl(Prima::Image::tiff)
Provides:       perl(Prima::Image::webp)
Provides:       perl(Prima::ImageViewer)
Provides:       perl(Prima::IniFile)
Provides:       perl(Prima::IniFile::Section::Helper::to::Tie)
Provides:       perl(Prima::InputLine)
Provides:       perl(Prima::InternalDockerShuttle)
Provides:       perl(Prima::KeySelector)
Provides:       perl(Prima::KeySelector::Dialog)
Provides:       perl(Prima::KeySelector::MenuEditor)
Provides:       perl(Prima::Label)
Provides:       perl(Prima::LinearDockerShuttle)
Provides:       perl(Prima::LinearWidgetDocker)
Provides:       perl(Prima::ListBox)
Provides:       perl(Prima::ListViewer)
Provides:       perl(Prima::Lists)
Provides:       perl(Prima::MDI)
Provides:       perl(Prima::MDIMethods)
Provides:       perl(Prima::MDIOwner)
Provides:       perl(Prima::MDIWindowOwner)
Provides:       perl(Prima::MainWindow)
Provides:       perl(Prima::Matrix)
Provides:       perl(Prima::Menu)
Provides:       perl(Prima::Menu::Bar)
Provides:       perl(Prima::Menu::Common)
Provides:       perl(Prima::Menu::Item)
Provides:       perl(Prima::Menu::Item::Custom)
Provides:       perl(Prima::Menu::Item::Guillemots)
Provides:       perl(Prima::Menu::Item::Image)
Provides:       perl(Prima::Menu::Item::Separator)
Provides:       perl(Prima::Menu::Item::Simple)
Provides:       perl(Prima::Menu::Item::Text)
Provides:       perl(Prima::Menu::Popup)
Provides:       perl(Prima::Menu::Root)
Provides:       perl(Prima::Menu::Transient)
Provides:       perl(Prima::MenuItem)
Provides:       perl(Prima::Menus)
Provides:       perl(Prima::MsgBox)
Provides:       perl(Prima::Notebook)
Provides:       perl(Prima::Notebooks)
Provides:       perl(Prima::Object)
Provides:       perl(Prima::Outline)
Provides:       perl(Prima::OutlineViewer)
Provides:       perl(Prima::Outlines)
Provides:       perl(Prima::PS::CFF)
Provides:       perl(Prima::PS::Drawable)
Provides:       perl(Prima::PS::File)
Provides:       perl(Prima::PS::File::Common)
Provides:       perl(Prima::PS::FileHandle)
Provides:       perl(Prima::PS::FileHandle::Common)
Provides:       perl(Prima::PS::Format)
Provides:       perl(Prima::PS::Glyphs)
Provides:       perl(Prima::PS::LPR)
Provides:       perl(Prima::PS::PDF)
Provides:       perl(Prima::PS::PDF::File)
Provides:       perl(Prima::PS::PDF::FileHandle)
Provides:       perl(Prima::PS::PDF::NonGUI)
Provides:       perl(Prima::PS::PDF::Printer)
Provides:       perl(Prima::PS::Pipe)
Provides:       perl(Prima::PS::PostScript)
Provides:       perl(Prima::PS::Printer)
Provides:       perl(Prima::PS::Printer::Common)
Provides:       perl(Prima::PS::Printer::NonGUI)
Provides:       perl(Prima::PS::TempFile)
Provides:       perl(Prima::PS::Type1)
Provides:       perl(Prima::PS::Unicode)
Provides:       perl(Prima::PodView)
Provides:       perl(Prima::PodViewWindow)
Provides:       perl(Prima::Popup)
Provides:       perl(Prima::PopupButton)
Provides:       perl(Prima::Printer)
Provides:       perl(Prima::ProgressBar)
Provides:       perl(Prima::ProtectedListBox)
Provides:       perl(Prima::Radio)
Provides:       perl(Prima::Region)
Provides:       perl(Prima::SampleWidget)
Provides:       perl(Prima::ScrollBar)
Provides:       perl(Prima::ScrollNotebook)
Provides:       perl(Prima::ScrollNotebook::Client)
Provides:       perl(Prima::SimpleWidgetDocker)
Provides:       perl(Prima::SingleLinearWidgetDocker)
Provides:       perl(Prima::Slider)
Provides:       perl(Prima::Sliders)
Provides:       perl(Prima::SpeedButton)
Provides:       perl(Prima::SpinButton)
Provides:       perl(Prima::SpinEdit)
Provides:       perl(Prima::Spinner)
Provides:       perl(Prima::StdBitmap)
Provides:       perl(Prima::Stress)
Provides:       perl(Prima::StringOutline)
Provides:       perl(Prima::TabSet)
Provides:       perl(Prima::TabbedNotebook)
Provides:       perl(Prima::TabbedScrollNotebook)
Provides:       perl(Prima::TabbedScrollNotebook::Client)
Provides:       perl(Prima::TextView)
Provides:       perl(Prima::Themes)
Provides:       perl(Prima::Themes::Proxy)
Provides:       perl(Prima::Themes::Round3D)
Provides:       perl(Prima::Themes::color)
Provides:       perl(Prima::Themes::flat)
Provides:       perl(Prima::Tie::Array)
Provides:       perl(Prima::Tie::Scalar)
Provides:       perl(Prima::Tie::items)
Provides:       perl(Prima::Tie::text)
Provides:       perl(Prima::Tie::value)
Provides:       perl(Prima::Timer)
Provides:       perl(Prima::Utils)
Provides:       perl(Prima::VB::AbstractGrid)
Provides:       perl(Prima::VB::AbstractOutline)
Provides:       perl(Prima::VB::AbstractSlider)
Provides:       perl(Prima::VB::AltSpinButton)
Provides:       perl(Prima::VB::ArrayOutline)
Provides:       perl(Prima::VB::BiScroller)
Provides:       perl(Prima::VB::Button)
Provides:       perl(Prima::VB::Calendar)
Provides:       perl(Prima::VB::CfgMaint)
Provides:       perl(Prima::VB::CheckBox)
Provides:       perl(Prima::VB::CheckList)
Provides:       perl(Prima::VB::CircularSlider)
Provides:       perl(Prima::VB::Classes)
Provides:       perl(Prima::VB::Cluster)
Provides:       perl(Prima::VB::CodeEditor)
Provides:       perl(Prima::VB::ColorComboBox)
Provides:       perl(Prima::VB::ComboBox)
Provides:       perl(Prima::VB::CommonControl)
Provides:       perl(Prima::VB::Component)
Provides:       perl(Prima::VB::Config)
Provides:       perl(Prima::VB::Control)
Provides:       perl(Prima::VB::CoreClasses)
Provides:       perl(Prima::VB::Date)
Provides:       perl(Prima::VB::DateTime)
Provides:       perl(Prima::VB::DetailedList)
Provides:       perl(Prima::VB::DetailedOutline)
Provides:       perl(Prima::VB::DirectoryListBox)
Provides:       perl(Prima::VB::DirectoryOutline)
Provides:       perl(Prima::VB::Divider)
Provides:       perl(Prima::VB::Drawable)
Provides:       perl(Prima::VB::DriveComboBox)
Provides:       perl(Prima::VB::Edit)
Provides:       perl(Prima::VB::Editor)
Provides:       perl(Prima::VB::FrameSet)
Provides:       perl(Prima::VB::Gauge)
Provides:       perl(Prima::VB::Grid)
Provides:       perl(Prima::VB::GroupBox)
Provides:       perl(Prima::VB::Header)
Provides:       perl(Prima::VB::ImageViewer)
Provides:       perl(Prima::VB::InputLine)
Provides:       perl(Prima::VB::ItemsOutline)
Provides:       perl(Prima::VB::KeySelector)
Provides:       perl(Prima::VB::Label)
Provides:       perl(Prima::VB::ListBox)
Provides:       perl(Prima::VB::ListViewer)
Provides:       perl(Prima::VB::MPropListViewer)
Provides:       perl(Prima::VB::MenuOutline)
Provides:       perl(Prima::VB::MyOutline)
Provides:       perl(Prima::VB::Notebook)
Provides:       perl(Prima::VB::Object)
Provides:       perl(Prima::VB::OutlineViewer)
Provides:       perl(Prima::VB::PackPropListViewer)
Provides:       perl(Prima::VB::ProgressBar)
Provides:       perl(Prima::VB::PropListViewer)
Provides:       perl(Prima::VB::Radio)
Provides:       perl(Prima::VB::ScrollBar)
Provides:       perl(Prima::VB::ScrollWidget)
Provides:       perl(Prima::VB::Slider)
Provides:       perl(Prima::VB::SpinButton)
Provides:       perl(Prima::VB::SpinEdit)
Provides:       perl(Prima::VB::StringOutline)
Provides:       perl(Prima::VB::TabSet)
Provides:       perl(Prima::VB::TabbedNotebook)
Provides:       perl(Prima::VB::Time)
Provides:       perl(Prima::VB::Types)
Provides:       perl(Prima::VB::Types::FMAction)
Provides:       perl(Prima::VB::Types::Handle)
Provides:       perl(Prima::VB::Types::align)
Provides:       perl(Prima::VB::Types::bool)
Provides:       perl(Prima::VB::Types::borderIcons)
Provides:       perl(Prima::VB::Types::borderStyle)
Provides:       perl(Prima::VB::Types::char)
Provides:       perl(Prima::VB::Types::checkbox)
Provides:       perl(Prima::VB::Types::cluster)
Provides:       perl(Prima::VB::Types::color)
Provides:       perl(Prima::VB::Types::comboStyle)
Provides:       perl(Prima::VB::Types::event)
Provides:       perl(Prima::VB::Types::fallback)
Provides:       perl(Prima::VB::Types::font)
Provides:       perl(Prima::VB::Types::gaugeRelief)
Provides:       perl(Prima::VB::Types::generic)
Provides:       perl(Prima::VB::Types::geometry)
Provides:       perl(Prima::VB::Types::growMode)
Provides:       perl(Prima::VB::Types::icon)
Provides:       perl(Prima::VB::Types::image)
Provides:       perl(Prima::VB::Types::items)
Provides:       perl(Prima::VB::Types::iv)
Provides:       perl(Prima::VB::Types::key)
Provides:       perl(Prima::VB::Types::lineRoundStyle)
Provides:       perl(Prima::VB::Types::menuItems)
Provides:       perl(Prima::VB::Types::menuname)
Provides:       perl(Prima::VB::Types::multiItems)
Provides:       perl(Prima::VB::Types::name)
Provides:       perl(Prima::VB::Types::origin)
Provides:       perl(Prima::VB::Types::packInfo)
Provides:       perl(Prima::VB::Types::pack_anchor)
Provides:       perl(Prima::VB::Types::pack_fill)
Provides:       perl(Prima::VB::Types::pack_side)
Provides:       perl(Prima::VB::Types::point)
Provides:       perl(Prima::VB::Types::radio)
Provides:       perl(Prima::VB::Types::rect)
Provides:       perl(Prima::VB::Types::rop)
Provides:       perl(Prima::VB::Types::selectingButtons)
Provides:       perl(Prima::VB::Types::sliderScheme)
Provides:       perl(Prima::VB::Types::string)
Provides:       perl(Prima::VB::Types::strings)
Provides:       perl(Prima::VB::Types::tabOrder)
Provides:       perl(Prima::VB::Types::text)
Provides:       perl(Prima::VB::Types::textee)
Provides:       perl(Prima::VB::Types::tickAlign)
Provides:       perl(Prima::VB::Types::treeArrays)
Provides:       perl(Prima::VB::Types::treeItems)
Provides:       perl(Prima::VB::Types::uiv)
Provides:       perl(Prima::VB::Types::uiv_undef)
Provides:       perl(Prima::VB::Types::upoint)
Provides:       perl(Prima::VB::Types::urect)
Provides:       perl(Prima::VB::Types::valign)
Provides:       perl(Prima::VB::Types::widgetClass)
Provides:       perl(Prima::VB::Types::windowState)
Provides:       perl(Prima::VB::VBControls)
Provides:       perl(Prima::VB::VBLoader)
Provides:       perl(Prima::VB::Widget)
Provides:       perl(Prima::VB::Window)
Provides:       perl(Prima::VB::examples::SampleWidget)
Provides:       perl(Prima::VB::examples::Widgety)
Provides:       perl(Prima::Widget)
Provides:       perl(Prima::Widget::BidiInput)
Provides:       perl(Prima::Widget::Date)
Provides:       perl(Prima::Widget::Date::Input)
Provides:       perl(Prima::Widget::Date::List)
Provides:       perl(Prima::Widget::EventRectangles)
Provides:       perl(Prima::Widget::Fader)
Provides:       perl(Prima::Widget::GroupScroller)
Provides:       perl(Prima::Widget::Header)
Provides:       perl(Prima::Widget::IntIndents)
Provides:       perl(Prima::Widget::Link)
Provides:       perl(Prima::Widget::ListBoxUtils)
Provides:       perl(Prima::Widget::MouseScroller)
Provides:       perl(Prima::Widget::Panel)
Provides:       perl(Prima::Widget::RubberBand)
Provides:       perl(Prima::Widget::ScrollGroup)
Provides:       perl(Prima::Widget::ScrollGroup::Client)
Provides:       perl(Prima::Widget::ScrollWidget)
Provides:       perl(Prima::Widget::StartupWindow)
Provides:       perl(Prima::Widget::Time)
Provides:       perl(Prima::Widget::UndoActions)
Provides:       perl(Prima::Window)
Provides:       perl(Prima::array)
Provides:       perl(Prima::matrix)
Provides:       perl(Prima::noX11)
Provides:       perl(Prima::rect)
Provides:       perl(Prima::sys::AnyEvent)
Provides:       perl(Prima::sys::FS)
Provides:       perl(Prima::sys::GUIException)
Provides:       perl(Prima::sys::Gencls)
Provides:       perl(Prima::sys::Test)
Provides:       perl(Prima::sys::XQuartz)
Provides:       perl(Prima::sys::gtk::FileDialog)
Provides:       perl(Prima::sys::gtk::OpenDialog)
Provides:       perl(Prima::sys::gtk::SaveDialog)
Provides:       perl(Prima::sys::win32)
Provides:       perl(Prima::sys::win32::FileDialog)
Provides:       perl(Prima::sys::win32::OpenDialog)
Provides:       perl(Prima::sys::win32::SaveDialog)
Provides:       perl(Prima::themes::sysimage)
%undefine       __perllib_provides
%{perl_requires}
# MANUAL BEGIN
BuildRequires:  giflib-devel
BuildRequires:  libpng-devel
BuildRequires:  libtiff-devel
BuildRequires:  xkeyboard-config
BuildRequires:  xorg-x11
BuildRequires:  xorg-x11-Xvfb
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(xcomposite)
BuildRequires:  pkgconfig(xcursor)
BuildRequires:  pkgconfig(xext)
BuildRequires:  pkgconfig(xft)
BuildRequires:  pkgconfig(xpm)
BuildRequires:  pkgconfig(xproto)
BuildRequires:  pkgconfig(xrandr)
BuildRequires:  pkgconfig(xrender)
%define         X_display         ":98"
Requires:       xorg-x11
# MANUAL END

%description
Prima is a classic 2D GUI toolkit that works under Windows and X11
environments. The toolkit features a rich widget library, extensive 2D
graphic support, PDF generation, modern Unicode text input and output, and
supports a wide set of image formats. Additionally, the RAD-style Visual
Builder and POD viewer are included. The toolkit can interoperate with
other popular event loop libraries.

%prep
%autosetup -n %{cpan_name}-%{cpan_version} -p1

find . -type f ! -path "*/t/*" ! -name "*.pl" ! -path "*/bin/*" ! -path "*/script/*" ! -path "*/scripts/*" ! -name "configure" -print0 | xargs -0 chmod 644

%build
perl Makefile.PL INSTALLDIRS=vendor OPTIMIZE="%{optflags}"
%make_build

%check
make test

%install
%perl_make_install
%perl_process_packlist
# MANUAL BEGIN
## oops, Prima/Config.pm must not contain BUILD_ROOT
find $RPM_BUILD_ROOT -name 'Config.pm' -print0 | xargs -0 perl -i -pe "s{\\Q$RPM_BUILD_ROOT}"'{}g'
###
### should these go to a perl-Prima-devel ?
find $RPM_BUILD_ROOT/%{perl_vendorarch} -name \*.h | xargs -t rm
# MANUAL END
%perl_gen_filelist

%files -f %{name}.files
%doc AGPLv3 Changes examples README.md
%license Copying LICENSE

%changelog
