#Type Name     ID    GECOS              Home directory    Shell
u     lact     -     "LACT daemon user" /var/lib/lact     /usr/sbin/nologin
g     lact     -     -                  -                 -
m     lact     lact  -                  -                 -
