# Main runtime directory
d   /run/net-snmp       0755    root    root    -

# AgentX socket directory
d   /run/agentx     0755    root    root    -

# Compatibility symlink for legacy software expecting /var/agentx
L   /var/agentx     -   -   -   -   /run/agentx

# State directory (also created by systemd StateDirectory=)
d   /var/lib/net-snmp   0755    root    root    -

# Log directory (also created by systemd LogsDirectory=)
d   /var/log/net-snmp   0755    root    root    -

