#
# spec file for package mozc
#
# Copyright (c) 2023 SUSE LLC
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Please submit bugfixes or comments via https://bugs.opensuse.org/
#


%global flavor @BUILD_FLAVOR@%{nil}

%if "%flavor" == "fcitx5"
%define with_fcitx4 0
%define with_fcitx5 1
%define install_mozc 0
%else
%define with_fcitx4 1
%define with_fcitx5 0
%define install_mozc 1
%endif

%if %{with_fcitx4}
%define fcitx_icon_dir %{_datadir}/fcitx/mozc/icon/
%define fcitx_addon_dir %{_datadir}/fcitx/addon/
%define fcitx_inputmethod_dir %{_datadir}/fcitx/inputmethod/
%define fcitx_lib_dir %{_libdir}/fcitx/
%endif

%if %{with_fcitx5}
%define fcitx5_addon_dir %{_datadir}/fcitx5/addon/
%define fcitx5_inputmethod_dir %{_datadir}/fcitx5/inputmethod/
%define fcitx5_lib_dir %{_libdir}/fcitx5/
%endif

%define server_dir %{_libdir}/mozc
%define ibus_mozc_path %{_libdir}/ibus-mozc/ibus-engine-mozc
%define ibus_mozc_icon_path %{_datadir}/ibus-mozc/product_icon.png
%define document_dir %{_docdir}/ibus-mozc
%define use_libprotobuf 0
%define bz_cachdir %{_sourcedir}/BAZEL_CACHE
%define makebazelcache() mkdir -p %{bz_cachdir}/content_addressable/sha256/%{?2:%2}%{?!2:$(sha256sum %1 | cut -f 1 -d ' ')}/; cp %1 %{bz_cachdir}/content_addressable/sha256/%{?2:%2}%{?!2:$(sha256sum %1 | cut -f 1 -d ' ')}/file ;

Name:           mozc
Version:        2.28.4715.102
Release:        0
Summary:        Mozc - Japanese Input Method for Chromium OS, Mac and Linux
License:        Apache-2.0 AND BSD-3-Clause AND SUSE-Public-Domain
Group:          System/I18n/Japanese
ExcludeArch:    ppc ppc64 s390 s390x %{ix86}
URL:            https://github.com/google/mozc
# Run ./make_archive.sh to make tar.xz removing third party files
Source0:        %{name}-%{version}.tar.xz
Source1:        README.SUSE
Source4:        ibus-setup-mozc-jp.desktop.in
#
# svn export http://japanese-usage-dictionary.googlecode.com/svn/trunk/@r10
# japanese-usage-dictionary
# License: BSD-2-Clause
Source5:        japanese_usage_dictionary-r10.tar.xz
# protobuf (without third party code)
# License: BSD-3-Clause
#
# Bazel requires static protobuf
# https://github.com/protocolbuffers/protobuf/archive/refs/tags/v3.19.3.tar.gz
Source6:        protobuf-v3.19.3.tar.gz
# abseil cpp
# License: Apache-2.0
# https://github.com/abseil/abseil-cpp/archive/refs/tags/20211102.0.tar.gz
Source7:        abseil-cpp-20211102.0.tar.gz
#
# jigyosyo.zip and ken_all.zip are zip-code--address data provided by
# Japan Post Co., Ltd.
# License: SUSE-Public-Domain
# Run ./make_archive.sh to download the latest files
Source10:       jigyosyo.zip
Source11:       ken_all.zip
# material design icons
# License: Apache-2.0
Source12:       material-design-icons.tar.xz
#
# add fcitx as mozc module
# License: BSD-3-Clause
# https://github.com/fcitx/mozc/tree/fcitx/src/unix/fcitx{,5}
# Run ./make_archive.sh to make tar.xz
%if %{with_fcitx4} || %{with_fcitx5}
Source20:       fcitx-mozc-27a5bd7e.tar.xz
Source21:       fcitx-mozc-icons.tar.gz
Patch20:        fcitx-mozc-bazel-build.patch
%endif
# A script for making a source tar.xz archive
Source100:      make_archive.sh
Source101:      add-sha256sum-for-zipcode-archives.patch.in

# PATCH-FEATURE-OPENSUSE ftake@geeko.jp
Patch1:         ibus-provide-layout-variations.patch
# PATCH-FIX-OPENSUSE fcitx5-mozc-fix.patch tiwai@suse.de -- Fix config of fcitx5-mozc
Patch9:         fcitx5-mozc-fix.patch
# PATCH-FIX-OPENSUSE add-sha256sum-for-zipcode-archives.patch ftake@geeko.jp -- to avoid download
# generated by ./make_archive.sh
Patch10:        add-sha256sum-for-zipcode-archives.patch
# PATCH-FIX-UPSTREAM add-missing-include.patch -- Add a missing include <cstdint>
Patch11:        add-missing-include.patch

BuildRequires:  bazel
BuildRequires:  bazel-apple-support-source
BuildRequires:  bazel-rules-apple-source
BuildRequires:  bazel-rules-cc-source
BuildRequires:  bazel-rules-java-source
BuildRequires:  bazel-rules-proto-source
BuildRequires:  bazel-rules-python-source
BuildRequires:  bazel-rules-swift-source
BuildRequires:  bazel-skylib-source
BuildRequires:  bazel-workspaces
%if 0%{?suse_version} == 1500
BuildRequires:  gcc8-c++
%endif
%if %{use_libprotobuf}
BuildRequires:  protobuf-devel
%endif
#BuildRequires:  python3
#BuildRequires:  python3-six
BuildRequires:  unzip
BuildRequires:  update-desktop-files
BuildRequires:  zlib-devel
BuildRoot:      %{_tmppath}/%{name}-%{version}-build

%description
Mozc is a Japanese Input Method Editor (IME) designed for
multi-platform such as Chromium OS, Mac and Linux. This open-source
project originates from Google Japanese Input.

%package -n ibus-mozc
Summary:        The Mozc engine for IBus
Group:          System/I18n/Japanese
BuildRequires:  ibus-devel
Requires:       ibus >= 1.4.1
Requires:       mozc = %{version}
Requires:       mozc-gui-tools = %{version}
Recommends:     ibus-mozc-candidate-window
Provides:       locale(ibus:ja)

%description -n ibus-mozc
The Mozc engine for IBus provides a Japanese input method.

%package -n ibus-mozc-candidate-window
Summary:        An optional candidate window for ibus-mozc
Group:          System/I18n/Japanese
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
Requires:       ibus-mozc = %{version}
Provides:       locale(ibus:ja)

%description -n ibus-mozc-candidate-window
This package provides an advanced candidate window for IBus. The
window shows examples of selected words.

%if %{with_fcitx4}
%package -n fcitx-mozc
Summary:        The Mozc backend for Fcitx
Group:          System/I18n/Japanese
BuildRequires:  fcitx-devel
Requires:       fcitx
Requires:       mozc = %{version}
Requires:       mozc-gui-tools = %{version}
Provides:       locale(fcitx:ja)

%description -n fcitx-mozc
The Mozc backend for Fcitx provides a Japanese input method.
%endif

%if %{with_fcitx5}
%package -n fcitx5-mozc
Summary:        The Mozc backend for Fcitx 5
Group:          System/I18n/Japanese
BuildRequires:  fcitx5-devel
Requires:       fcitx5
Requires:       mozc = %{version}
Requires:       mozc-gui-tools = %{version}
Provides:       locale(fcitx5:ja)

%description -n fcitx5-mozc
The Mozc backend for Fcitx 5 provides a Japanese input method.
%endif

%package gui-tools
Summary:        GUI tools for mozc
Group:          System/I18n/Japanese
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
Requires:       mozc = %{version}

%description gui-tools
This package provides config, word-register, dictioaly,
character-palette tools.

%prep
%setup -q

# extract fcitx-mozc
%if %{with_fcitx4} || %{with_fcitx5}
tar xvf %{SOURCE20}
%patch20 -p1
#patch21 -p1
%endif

%patch1 -p1

cp %{SOURCE1} .

# install third_party files
cd src/third_party
# japanese_usage_dictionary
tar xvf %{SOURCE5}
# protobuf
%if ! %{use_libprotobuf}
mkdir protobuf
tar xvf %{SOURCE6} -C protobuf --strip-components 1
%endif
# abseil
tar xvf %{SOURCE7}
mv abseil-cpp-20211102.0 abseil-cpp
cd ../..

%if %{with_fcitx5}
%patch9 -p1
%endif
%patch10 -p1
%patch11 -p1

# fix installation, library and header path
sed -e 's|@libdir@|%{_libdir}|g' %{SOURCE4} > ibus-setup-mozc-jp.desktop
sed -i -e 's|lib/x86_64-linux-gnu|%{_lib}|g' src/BUILD.ibus.bazel

sed -i -e 's|^\(LINUX_MOZC_DOCUMENT_DIR = \).*|\1 "%{_docdir}/%{name}"|' src/config.bzl
sed -i -e 's|^\(LINUX_MOZC_SERVER_DIR = \).*|\1 "%{_libdir}/mozc"|' src/config.bzl
sed -i -e 's|^\(IBUS_MOZC_PATH = \).*|\1 "%{_libdir}/ibus-mozc/ibus-engine-mozc"|' src/config.bzl
sed -i -e 's|^\(QT_BASE_PATH = \).*|\1 "/usr/include/qt5"|' src/config.bzl
sed -i -e 's|^\(QT_BIN_PATH = \).*|\1 "%{_libdir}/qt5/bin/"|' src/config.bzl

# prepare zip code dictionary
%makebazelcache %{SOURCE10}
%makebazelcache %{SOURCE11}

# icons
tar xvf %{SOURCE12}
%makebazelcache material-design-icons/dictionary.png
%makebazelcache material-design-icons/dictionary.svg
%makebazelcache material-design-icons/properties.png
%makebazelcache material-design-icons/properties.svg
%makebazelcache material-design-icons/tool.png
%makebazelcache material-design-icons/tool.svg

%build

cd src

%if 0%{?suse_version} == 1500
export CC=gcc-8
export CXX=g++-8
%endif

for f in %{optflags}; do
	dist_opt_flags="$dist_opt_flags --copt $f"
done

# Be careful bazel cache is not cleared by `obs build`
# --output_base might help

bazel build package \
%if %{with_fcitx4}
	"//unix/fcitx:fcitx-mozc.so" \
%endif
%if %{with_fcitx5}
	"//unix/fcitx5:fcitx5-mozc.so" \
%endif
	--repository_cache=%{bz_cachdir} \
	--config oss_linux \
	-c opt \
	$dist_opt_flags \
	--force_pic \
	--jobs %{?jobs} \
	--strip=never \
	--sandbox_debug \
	--verbose_failures \
	-s \
	--override_repository="rules_cc=/usr/src/bazel-rules-cc" \
	--override_repository="rules_java=/usr/src/bazel-rules-java" \
	--override_repository="rules_python=/usr/src/bazel-rules-python" \
	--override_repository="rules_proto=/usr/src/bazel-rules-proto" \
	--override_repository="build_bazel_rules_apple=/usr/src/bazel-rules-apple" \
	--override_repository="build_bazel_apple_support=/usr/src/bazel-apple-support" \
	--override_repository="build_bazel_rules_swift=/usr/src/bazel-rules-swift" \
	--override_repository="bazel_skylib=/usr/src/bazel-skylib" \
	--override_repository="zlib=/usr/share/bazel-workspaces/zlib" \

bazel shutdown

%define output_dir src/bazel-bin

%if %{with_fcitx4}
cd unix/fcitx
./gen_fcitx_mozc_i18n.sh ../../../%{output_dir}/unix/fcitx/po
%endif
%if %{with_fcitx5}
cd unix/fcitx5
../fcitx/gen_fcitx_mozc_i18n.sh ../../../%{output_dir}/unix/fcitx5/po
%endif

%install

%if %{install_mozc}
install -m755 -d %{buildroot}%{_libdir}/ibus-mozc
install -m755 %{output_dir}/unix/ibus/ibus_mozc %{buildroot}%{_libdir}/ibus-mozc/ibus-engine-mozc
install -m755 -d %{buildroot}%{_datadir}/ibus/component
install -m644 %{output_dir}/unix/ibus/mozc.xml %{buildroot}%{_datadir}/ibus/component/mozc.xml
install -m755 -d %{buildroot}%{_datadir}/ibus-mozc
unzip %{output_dir}/unix/icons.zip -d %{buildroot}%{_datadir}/ibus-mozc/

install -m755 -d %{buildroot}%{_datadir}/applications
install -m644 ibus-setup-mozc-jp.desktop %{buildroot}%{_datadir}/applications/ibus-setup-mozc-jp.desktop
%suse_update_desktop_file ibus-setup-mozc-jp System X-SuSE-Core-System

# for provide-layout-variations patch
ln -s ibus-setup-mozc-jp.desktop %{buildroot}%{_datadir}/applications/ibus-setup-mozc-jp-jp.desktop
%suse_update_desktop_file ibus-setup-mozc-jp-jp System X-SuSE-Core-System
ln -s ibus-setup-mozc-jp.desktop %{buildroot}%{_datadir}/applications/ibus-setup-mozc-us.desktop
%suse_update_desktop_file ibus-setup-mozc-us System X-SuSE-Core-System
ln -s ibus-setup-mozc-jp.desktop %{buildroot}%{_datadir}/applications/ibus-setup-mozc-dv.desktop
%suse_update_desktop_file ibus-setup-mozc-dv System X-SuSE-Core-System
%endif

%if %{with_fcitx4}
# Install Fcitx module
for mofile in %{output_dir}/unix/fcitx/po/*.mo
do
	filename=`basename $mofile`
	lang=${filename/.mo/}
	install -D -m 644 "$mofile" "%{buildroot}%{_datadir}/locale/$lang/LC_MESSAGES/fcitx-mozc.mo"
done
install -m755 -d %{buildroot}%{fcitx_addon_dir}
install -m755 -d %{buildroot}%{fcitx_inputmethod_dir}
install -m755 -d %{buildroot}%{fcitx_icon_dir}
install -m755 -d %{buildroot}%{fcitx_lib_dir}
install -m 755 %{output_dir}/unix/fcitx/fcitx-mozc.so %{buildroot}%{fcitx_lib_dir}/fcitx-mozc.so
install -m 644 src/unix/fcitx/fcitx-mozc.conf %{buildroot}%{fcitx_addon_dir}
install -m 644 src/unix/fcitx/mozc.conf %{buildroot}%{fcitx_inputmethod_dir}
install -m 644 src/data/images/product_icon_32bpp-128.png %{buildroot}%{fcitx_icon_dir}/mozc.png
install -m 644 src/data/images/unix/ui-alpha_full.png %{buildroot}%{fcitx_icon_dir}/mozc-alpha_full.png
install -m 644 src/data/images/unix/ui-alpha_half.png %{buildroot}%{fcitx_icon_dir}/mozc-alpha_half.png
install -m 644 src/data/images/unix/ui-direct.png %{buildroot}%{fcitx_icon_dir}/mozc-direct.png
install -m 644 src/data/images/unix/ui-hiragana.png %{buildroot}%{fcitx_icon_dir}/mozc-hiragana.png
install -m 644 src/data/images/unix/ui-katakana_full.png %{buildroot}%{fcitx_icon_dir}/mozc-katakana_full.png
install -m 644 src/data/images/unix/ui-katakana_half.png %{buildroot}%{fcitx_icon_dir}/mozc-katakana_half.png
install -m 644 src/data/images/unix/ui-dictionary.png %{buildroot}%{fcitx_icon_dir}/mozc-dictionary.png
install -m 644 src/data/images/unix/ui-properties.png %{buildroot}%{fcitx_icon_dir}/mozc-properties.png
install -m 644 src/data/images/unix/ui-tool.png %{buildroot}%{fcitx_icon_dir}/mozc-tool.png

# fix mozc icons. they're too ugly that even lose face for openSUSE.
cp -r %{SOURCE21} ./
tar -xzf fcitx-mozc-icons.tar.gz
cp -r fcitx-mozc-icons/* %{buildroot}%{fcitx_icon_dir}/
rm -rf fcitx-mozc-icons
rm -rf fcitx-mozc-icons.tar.gz
%endif

%if %{with_fcitx5}
# Install Fcitx5 module
for mofile in %{output_dir}/unix/fcitx5/po/*.mo
do
	filename=`basename $mofile`
	lang=${filename/.mo/}
	install -D -m 644 "$mofile" "%{buildroot}%{_datadir}/locale/$lang/LC_MESSAGES/fcitx5-mozc.mo"
done
install -m755 -d %{buildroot}%{fcitx5_addon_dir}
install -m755 -d %{buildroot}%{fcitx5_inputmethod_dir}
install -m755 -d %{buildroot}%{fcitx5_lib_dir}
install -m 755 %{output_dir}/unix/fcitx5/fcitx5-mozc.so %{buildroot}%{fcitx5_lib_dir}/mozc.so
install -m 644 src/unix/fcitx5/mozc-addon.conf %{buildroot}%{fcitx5_addon_dir}/mozc.conf
install -m 644 src/unix/fcitx5/mozc.conf %{buildroot}%{fcitx5_inputmethod_dir}

unzip -d icons %{output_dir}/unix/icons.zip
install -D -m 644 src/data/images/product_icon_32bpp-128.png "%{buildroot}%{_datadir}/icons/hicolor/128x128/apps/org.fcitx.Fcitx5.fcitx-mozc.png"
install -D -m 644 src/data/images/unix/ime_product_icon_opensource-32.png "%{buildroot}%{_datadir}/icons/hicolor/32x32/apps/org.fcitx.Fcitx5.fcitx-mozc.png"
install -D -m 644 icons/mozc.svg "%{buildroot}%{_datadir}/icons/hicolor/scalable/apps/org.fcitx.Fcitx5.fcitx-mozc.svg"
install -D -m 644 icons/alpha_full.png "%{buildroot}%{_datadir}/icons/hicolor/48x48/apps/org.fcitx.Fcitx5.fcitx-mozc-alpha-full.png"
install -D -m 644 icons/alpha_half.png "%{buildroot}%{_datadir}/icons/hicolor/48x48/apps/org.fcitx.Fcitx5.fcitx-mozc-alpha-half.png"
install -D -m 644 icons/direct.png "%{buildroot}%{_datadir}/icons/hicolor/48x48/apps/org.fcitx.Fcitx5.fcitx-mozc-direct.png"
install -D -m 644 icons/hiragana.png "%{buildroot}%{_datadir}/icons/hicolor/48x48/apps/org.fcitx.Fcitx5.fcitx-mozc-hiragana.png"
install -D -m 644 icons/katakana_full.png "%{buildroot}%{_datadir}/icons/hicolor/48x48/apps/org.fcitx.Fcitx5.fcitx-mozc-katakana-full.png"
install -D -m 644 icons/katakana_half.png "%{buildroot}%{_datadir}/icons/hicolor/48x48/apps/org.fcitx.Fcitx5.fcitx-mozc-katakana-half.png"
install -D -m 644 icons/dictionary.png "%{buildroot}%{_datadir}/icons/hicolor/48x48/apps/org.fcitx.Fcitx5.fcitx-mozc-dictionary.png"
install -D -m 644 icons/properties.png "%{buildroot}%{_datadir}/icons/hicolor/48x48/apps/org.fcitx.Fcitx5.fcitx-mozc-properties.png"
install -D -m 644 icons/tool.png "%{buildroot}%{_datadir}/icons/hicolor/48x48/apps/org.fcitx.Fcitx5.fcitx-mozc-tool.png"

ln -sf org.fcitx.Fcitx5.fcitx-mozc.png "%{buildroot}%{_datadir}/icons/hicolor/128x128/apps/fcitx-mozc.png"
ln -sf org.fcitx.Fcitx5.fcitx-mozc.png "%{buildroot}%{_datadir}/icons/hicolor/32x32/apps/fcitx-mozc.png"
ln -sf org.fcitx.Fcitx5.fcitx-mozc.svg "%{buildroot}%{_datadir}/icons/hicolor/scalable/apps/fcitx-mozc.svg"
ln -sf org.fcitx.Fcitx5.fcitx-mozc-alpha-full.png "%{buildroot}%{_datadir}/icons/hicolor/48x48/apps/fcitx-mozc-alpha-full.png"
ln -sf org.fcitx.Fcitx5.fcitx-mozc-alpha-half.png "%{buildroot}%{_datadir}/icons/hicolor/48x48/apps/fcitx-mozc-alpha-half.png"
ln -sf org.fcitx.Fcitx5.fcitx-mozc-direct.png "%{buildroot}%{_datadir}/icons/hicolor/48x48/apps/fcitx-mozc-direct.png"
ln -sf org.fcitx.Fcitx5.fcitx-mozc-hiragana.png "%{buildroot}%{_datadir}/icons/hicolor/48x48/apps/fcitx-mozc-hiragana.png"
ln -sf org.fcitx.Fcitx5.fcitx-mozc-katakana-full.png "%{buildroot}%{_datadir}/icons/hicolor/48x48/apps/fcitx-mozc-katakana-full.png"
ln -sf org.fcitx.Fcitx5.fcitx-mozc-katakana-half.png "%{buildroot}%{_datadir}/icons/hicolor/48x48/apps/fcitx-mozc-katakana-half.png"
ln -sf org.fcitx.Fcitx5.fcitx-mozc-dictionary.png "%{buildroot}%{_datadir}/icons/hicolor/48x48/apps/fcitx-mozc-dictionary.png"
ln -sf org.fcitx.Fcitx5.fcitx-mozc-properties.png "%{buildroot}%{_datadir}/icons/hicolor/48x48/apps/fcitx-mozc-properties.png"
ln -sf org.fcitx.Fcitx5.fcitx-mozc-tool.png "%{buildroot}%{_datadir}/icons/hicolor/48x48/apps/fcitx-mozc-tool.png"

%endif

%if %{install_mozc}
install -m755 -d %{buildroot}%{server_dir}
install -m755 %{output_dir}/server/mozc_server %{buildroot}%{server_dir}
install -m755 %{output_dir}/gui/tool/mozc_tool %{buildroot}%{server_dir}
install -m755 %{output_dir}/renderer/mozc_renderer %{buildroot}%{server_dir}

install -m755 -d %{buildroot}%{_bindir}
install -m755 %{output_dir}/unix/emacs/mozc_emacs_helper %{buildroot}%{_bindir}
# install only for emacs since xemacs is not supported
install -m755 -d %{buildroot}%{_datadir}/emacs/site-lisp
install -m644 src/unix/emacs/mozc.el %{buildroot}%{_datadir}/emacs/site-lisp/

chmod 644 src/data/installer/credits_*.html
%endif

%if %{with_fcitx4}
%find_lang fcitx-mozc %no_lang_C
%endif

%if %{with_fcitx5}
%find_lang fcitx5-mozc %no_lang_C
%endif

%if %{install_mozc}
%files
%defattr(-, root, root)
%doc src/data/installer/credits_en.html
%doc README.SUSE
%dir %{server_dir}
%{server_dir}/mozc_server
%{_bindir}/mozc_emacs_helper
%dir %{_datadir}/emacs/site-lisp/
%{_datadir}/emacs/site-lisp/mozc.el

%files gui-tools
%defattr(-, root, root)
%{_libdir}/mozc/mozc_tool

%files -n ibus-mozc
%defattr(-, root, root)
%license material-design-icons/LICENSE-material-design-icons
%dir %{_libdir}/ibus-mozc/
%{_libdir}/ibus-mozc/ibus-engine-mozc
%{_datadir}/applications/ibus-setup-mozc-jp.desktop
%{_datadir}/applications/ibus-setup-mozc-jp-jp.desktop
%{_datadir}/applications/ibus-setup-mozc-us.desktop
%{_datadir}/applications/ibus-setup-mozc-dv.desktop
%dir %{_datadir}/ibus/component/
%{_datadir}/ibus/component/mozc.xml
%{_datadir}/ibus-mozc/

%files -n ibus-mozc-candidate-window
%defattr(-, root, root)
%{_libdir}/mozc/mozc_renderer
%endif

%if %{with_fcitx4}
%files -n fcitx-mozc -f fcitx-mozc.lang
%defattr(-,root,root)

%{fcitx_lib_dir}/fcitx-mozc.so
%{fcitx_addon_dir}/fcitx-mozc.conf
%dir %{fcitx_inputmethod_dir}
%{fcitx_inputmethod_dir}/mozc.conf
%dir %{_datadir}/fcitx/mozc
%dir %{fcitx_icon_dir}
%{fcitx_icon_dir}/mozc.png
%{fcitx_icon_dir}/mozc-alpha_full.png
%{fcitx_icon_dir}/mozc-alpha_half.png
%{fcitx_icon_dir}/mozc-direct.png
%{fcitx_icon_dir}/mozc-hiragana.png
%{fcitx_icon_dir}/mozc-katakana_full.png
%{fcitx_icon_dir}/mozc-katakana_half.png
%{fcitx_icon_dir}/mozc-dictionary.png
%{fcitx_icon_dir}/mozc-properties.png
%{fcitx_icon_dir}/mozc-tool.png
%endif

%if %{with_fcitx5}
%files -n fcitx5-mozc -f fcitx5-mozc.lang
%defattr(-,root,root)

%{fcitx5_lib_dir}/mozc.so
%{fcitx5_addon_dir}/mozc.conf
%dir %{fcitx5_inputmethod_dir}
%{fcitx5_inputmethod_dir}/mozc.conf
%{_datadir}/icons/hicolor/
%endif

%changelog
