#Type   Path                              Mode  User  Group   Age     Argument
d       /var/spool/anacron                0755  root  root    -       -
f       /var/spool/anacron/cron.daily     0644  root  root    -       -
f       /var/spool/anacron/cron.weekly    0644  root  root    -       -
f       /var/spool/anacron/cron.monthly   0644  root  root    -       -
