#
# spec file for package otpclient
#
# Copyright (c) 2026 SUSE LLC and contributors
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Please submit bugfixes or comments via https://bugs.opensuse.org/
#


%define uclname OTPClient
Name:           otpclient
Version:        5.1.4
Release:        0
Summary:        Simple GTK+ client for managing TOTP and HOTP
License:        GPL-3.0-or-later
Group:          Productivity/Security
URL:            https://github.com/paolostivanin/%{name}
Source0:        https://github.com/paolostivanin/%{name}/archive/v%{version}.tar.gz
Source1:        https://github.com/paolostivanin/%{uclname}/releases/download/v%{version}/v%{version}.tar.gz.asc
Source2:        otpclient.keyring
BuildRequires:  cmake
BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  pkgconfig
BuildRequires:  pkgconfig(glib-2.0) >= 2.68
BuildRequires:  pkgconfig(gtk4) >= 4.10.0
BuildRequires:  libgcrypt-devel >= 1.10.1
BuildRequires:  libcotp-devel >= 4.0.0
BuildRequires:  libuuid-devel >= 2.34.0
BuildRequires:  libsecret-devel >= 0.20
BuildRequires:  protobuf-devel >= 3.6.0
BuildRequires:  qrencode-devel >= 4.0.2
BuildRequires:  libadwaita-devel >= 1.5.0
BuildRequires:  libprotobuf-c-devel >= 1.3.0
BuildRequires:  libpng16-devel >= 1.6.30
BuildRequires:  libzbar-devel >= 0.20.0
BuildRequires:  libjansson-devel >= 2.12.0

%description
Highly secure and easy to use GTK+ software for two-factor authentication
that supports both Time-based One-time Passwords (TOTP) and
HMAC-Based One-Time Passwords (HOTP).

%package bash-completion
Summary:        Bash completion for %{name}
Group:          System/Shells
Requires:       %{name} = %{version}
Requires:       bash-completion
Supplements:    (%{name} and bash-completion)
BuildArch:      noarch

%description bash-completion
Bash command line completion support for %{name}.

%package zsh-completion
Summary:        Zsh completion for %{name}
Group:          System/Shells
Requires:       %{name} = %{version}
Requires:       zsh
Supplements:    (%{name} and zsh)
BuildArch:      noarch

%description zsh-completion
Zsh command line completion support for %{name}.

%package fish-completion
Summary:        Fish completion for %{name}
Group:          System/Shells
Requires:       %{name} = %{version}
Requires:       fish
Supplements:    (%{name} and fish)
BuildArch:      noarch

%description fish-completion
Fish command line completion support for %{name}.

%package gnome-search-provider
Summary:        GNOME Shell search provider for %{name}
Group:          Productivity/Security
Requires:       %{name} = %{version}
Requires:       gnome-shell
Supplements:    (%{name} and gnome-shell)
BuildArch:      noarch

%description gnome-search-provider
GNOME Shell search provider integration for %{name}, allowing OTP
codes to be looked up directly from the Activities overview.

%package krunner
Summary:        KRunner plugin for %{name}
Group:          Productivity/Security
Requires:       %{name} = %{version}
Requires:       kf6-krunner
Supplements:    (%{name} and kf6-krunner)
BuildArch:      noarch

%description krunner
KRunner integration for %{name}, allowing OTP codes to be looked up
directly from KRunner.

%prep
%autosetup -p1 -n %{uclname}-%{version}

%build
%cmake \
    -DCMAKE_INSTALL_PREFIX=%{_prefix} \
    -DBUILD_GUI=ON \
    -DBUILD_CLI=ON \
    -DENABLE_MINIMIZE_TO_TRAY=ON
%cmake_build

%install
%cmake_install
# Drop generated caches owned by glib2-tools / hicolor-icon-theme;
# they are regenerated by file triggers on install.
rm -f %{buildroot}%{_datadir}/glib-2.0/schemas/gschemas.compiled
rm -f %{buildroot}%{_datadir}/icons/hicolor/icon-theme.cache

%files
%license LICENSE
%doc README.md
%dir %{_datadir}/%{name}

%{_bindir}/%{name}
%{_bindir}/%{name}-cli
%{_bindir}/otpclient-search-provider

%{_datadir}/applications/com.github.paolostivanin.%{uclname}.desktop
%{_datadir}/metainfo/com.github.paolostivanin.%{uclname}.appdata.xml

%{_mandir}/man1/otpclient-cli.1%{?ext_man}
%{_mandir}/man1/otpclient.1%{?ext_man}

%{_datadir}/icons/hicolor/scalable/apps/com.github.paolostivanin.OTPClient-symbolic.svg
%{_datadir}/icons/hicolor/scalable/apps/com.github.paolostivanin.OTPClient.svg

%{_datadir}/glib-2.0/schemas/com.github.paolostivanin.OTPClient.gschema.xml
%{_datadir}/otpclient/window.ui

%files bash-completion
%{_datadir}/bash-completion/completions/otpclient-cli

%files zsh-completion
%{_datadir}/zsh/site-functions/_otpclient-cli

%files fish-completion
%dir %{_datadir}/fish
%dir %{_datadir}/fish/vendor_completions.d
%{_datadir}/fish/vendor_completions.d/otpclient-cli.fish

%files gnome-search-provider
%dir %{_datadir}/gnome-shell
%dir %{_datadir}/gnome-shell/search-providers
%{_datadir}/dbus-1/services/com.github.paolostivanin.OTPClient.SearchProvider.service
%{_datadir}/gnome-shell/search-providers/com.github.paolostivanin.OTPClient.SearchProvider.ini

%files krunner
%dir %{_datadir}/krunner
%dir %{_datadir}/krunner/dbusplugins
%{_datadir}/dbus-1/services/com.github.paolostivanin.OTPClient.KRunner.service
%{_datadir}/krunner/dbusplugins/com.github.paolostivanin.OTPClient.KRunner.desktop

%changelog
