#
# spec file for package unknown-horizons
#
# Copyright (c) 2019 SUSE LINUX GmbH, Nuernberg, Germany.
# Copyright (c) 2011 Nelson Marques <nmarques@opensuse.org>
# Copyright (c) Unknown Horizons, http://www.unknown-horizons.org
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Please submit bugfixes or comments via http://bugs.opensuse.org/
#


Name:           unknown-horizons
Version:        2019.1
Release:        0
Summary:        An economy and city building game
License:        APL-1.0 AND CC-BY-SA-3.0 AND GPL-2.0-with-font-exception AND MIT AND OFL-1.1
Group:          Amusements/Games/Strategy/Other
URL:            http://www.unknown-horizons.org
Source0:        https://github.com/%{name}/%{name}/archive/%{version}.tar.gz
# https://github.com/unknown-horizons/unknown-horizons/pull/2891
Patch0:         unknown-horizons-encoding.patch
BuildRequires:  docbook-xsl-stylesheets
BuildRequires:  fdupes
BuildRequires:  fife-devel >= 0.3.5
BuildRequires:  hicolor-icon-theme
BuildRequires:  intltool
BuildRequires:  pkgconfig
BuildRequires:  python3 >= 3.6.5
BuildRequires:  python3-Cython
BuildRequires:  python3-Pillow
BuildRequires:  python3-distutils-extra
BuildRequires:  python3-pathlib
BuildRequires:  python3-typing
BuildRequires:  update-desktop-files
BuildRequires:  pkgconfig(libexslt)
BuildRequires:  pkgconfig(libxslt)
Requires:       hicolor-icon-theme
Requires:       python3-Pillow
Requires:       python3-PyYAML
Requires:       python3-fife >= 0.3.5
Recommends:     %{name}-lang = %{version}
# python3-enet is only required for multiplayer and the game gracefully handles it not
# being present.
Recommends:     python3-enet
BuildArch:      noarch

%description
Unknown Horizons is a 2D realtime strategy simulation with an emphasis on
economy and city building. The player has to expand a small settlement to a strong and
wealthy colony, collect taxes and supply inhabitants with valuable
goods, and increase the power with a well balanced economy and with strategic
trade and diplomacy.

%lang_package

%prep
%setup -q
%patch0 -p1
find . -type f -exec sed -i "s/#!\/usr\/bin\/env python3/#!\/usr\/bin\/python3/" {} +

%build
python3 setup.py build

%install
python3 setup.py install --prefix=%{_prefix} --root=%{buildroot}

# For some reason the Atlas generated by setup.py is corrupted. It has more
# entries in the DB than there are image files. Regenaration fixes this.
rm -f content/gfx/atlas/*
rm -f content/atlas.sql
rm -f content/actionsets.json
rm -f content/tilesets.json
cd development
python3 ../horizons/engine/generate_atlases.py 2048
cd -

# -- we require use system pyenet
find %{buildroot}%{python_sitelib} -name "*enet.so" -type f -print -delete
# -- remove *egg-info
find %{buildroot}%{python_sitelib} -type f -name "*.egg-info" -print -delete

# Install vector icon and remove old one
install -D -m 0644 content/gui/images/logos/uh_no_text.svg \
    %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/%{name}.svg
rm -v %{buildroot}%{_datadir}/pixmaps/unknown-horizons.xpm

# Install the Atlas
install -D -m 0644 content/atlas.sql %{buildroot}%{_datadir}/%{name}/content/atlas.sql
install -D -m 0644 content/actionsets.json %{buildroot}%{_datadir}/%{name}/content/actionsets.json
install -D -m 0644 content/tilesets.json %{buildroot}%{_datadir}/%{name}/content/tilesets.json
install -m 0644 content/gfx/atlas/* %{buildroot}%{_datadir}/%{name}/content/gfx/atlas

# Remove file only existing to ensure directoy is not dropped by Git
rm -v %{buildroot}%{_datadir}/%{name}/content/gfx/atlas/.keepme

# Remove duplicate license files
rm -v %{buildroot}%{_datadir}/%{name}/content/fonts/{GPL_fontexception,OFL}

# Remove duplicate languages and find correct ones
rm -rfv %{buildroot}%{_datadir}/%{name}/content/lang

%find_lang %{name}
%find_lang %{name}-server

%suse_update_desktop_file -i -r -G "A RTS simulation game" %{name} StrategyGame Game
%fdupes %{buildroot}%{python_sitelib}
%fdupes %{buildroot}%{_datadir}

%post
%desktop_database_post
%icon_theme_cache_post

%postun
%desktop_database_postun
%icon_theme_cache_post

%files
%doc README.md doc/CHANGELOG.md
%if ( 0%{?suse_version} == 1315 && 0%{?sle_version} == 120100 ) || ! 0%{?is_opensuse}
# Leap 42.1 or SLE
%license doc/LICENSE
%doc doc/AUTHORS.md doc/licenses/
%else
%license doc/LICENSE doc/AUTHORS.md doc/licenses/
%endif
%{_bindir}/unknown-horizons
%{python3_sitelib}/horizons/
%{_datadir}/applications/%{name}.desktop
%{_datadir}/%{name}/
%{_datadir}/icons/*/*/*/%{name}.svg
%{_mandir}/man6/%{name}.6%{?ext_man}
%{_datadir}/locale/stats.json

%files lang -f %{name}-server.lang -f %{name}.lang

%changelog
