LXDE-Control-Center=
LXDM Settings=
Configure Openbox=
Mouse&Keyboard=
Set Wallpaper=
Screensaver Settings=
Appearance=
PCManFM Settings=
PCManFM Super User Mode=
Refresh Panel=
Install Software=
YaST Control Center=
Session Settings=
Monitor Settings=
