#
# spec file for package redis
#
# Copyright (c) 2026 SUSE LLC and contributors
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Please submit bugfixes or comments via https://bugs.opensuse.org/
#

%define requires_file() %( readlink -f '%*' | LC_ALL=C xargs -r rpm -q --qf 'Requires: %%{name} >= %%{epoch}:%%{version}\\n' -f | sed -e 's/ (none):/ /' -e 's/ 0:/ /' | grep -v "is not")

# Three multibuild flavours share this spec:
#
#   ""        the server itself -- the only flavour anything else in the
#             distribution build-depends on, so it is kept deliberately cheap:
#             no cmake, no rust, no python, and no test suite.
#   "test"    runs upstream's tcl test suite (~25 minutes). Split out so a
#             server rebuild during bootstrap does not have to wait for it.
#   "modules" the four modules upstream vendors under modules/ since 8.x.
#             They need cmake, rust and python on top of the server's own
#             dependencies, which is exactly why they must not be part of the
#             server flavour.
%global flavor @BUILD_FLAVOR@%{nil}
%if "%{flavor}" == "test"
%define psuffix -test
# This flavour packages nothing at all -- it exists to run the test suite --
# so do not leave a redis-test-debugsource behind either
%global debug_package %{nil}
%endif
%if "%{flavor}" == "modules"
%define psuffix -modules
%endif
%if "%{flavor}" == ""
%define psuffix %{nil}
%endif
# %%{name} carries the flavour suffix, so everything that names the upstream
# project -- paths, sources, the service units, the sysusers account -- has to
# go through %%{origname} instead.
%define origname       redis
%define _data_dir      %{_localstatedir}/lib/%{origname}
%define _log_dir       %{_localstatedir}/log/%{origname}
%define _conf_dir      %{_sysconfdir}/%{origname}
%define _module_dir    %{_libdir}/%{origname}/modules
Name:           %{origname}%{psuffix}
Version:        8.10.0
Release:        0
Summary:        Persistent key-value database
License:        AGPL-3.0-only
URL:            https://github.com/redis/redis
Source0:        https://download.redis.io/releases/%{origname}-%{version}.tar.gz
Source1:        %{origname}.logrotate
Source2:        %{origname}.target
Source3:        %{origname}@.service
Source4:        %{origname}.tmpfiles.d
Source5:        README.SUSE
Source6:        %{origname}.sysctl
Source7:        %{origname}-sentinel@.service
Source8:        %{origname}-sentinel.target
Source9:        %{origname}-user.conf
Source10:       https://raw.githubusercontent.com/redis/redis-hashes/master/README#/%{origname}.hashes
# PATCH-MISSING-TAG -- See https://wiki.opensuse.org/openSUSE:Packaging_Patches_guidelines
Source11:       series
# Generated by the two cargo_vendor runs in _service, "modules" flavour only
Source20:       vendor-redisearch.tar.zst
Source21:       vendor-redisjson.tar.zst
# The one dependency redisearch's bundled VectorSimilarity still clones from
# git once the SVS backend is off; there is no cpu_features package to build
# against. "modules" flavour only.
Source22:       https://github.com/google/cpu_features/archive/refs/tags/v0.10.1.tar.gz#/cpu_features-0.10.1.tar.gz
Patch0:         %{origname}-conf.patch
Patch1:         reproducible.patch
Patch2:         ppc-atomic.patch
# PATCH-FIX-UPSTREAM vectorsimilarity-guard-svs-include.patch mpluskal@suse.com -- USE_SVS=OFF does not compile, https://github.com/RedisAI/VectorSimilarity/pull/1006
Patch3:         vectorsimilarity-guard-svs-include.patch
# PATCH-FIX-UPSTREAM scripting-test-disable-aof-after-use.patch mpluskal@suse.com -- test leaves AOF on, racing the next test's SHUTDOWN NOSAVE, https://github.com/valkey-io/valkey/pull/1156
Patch4:         scripting-test-disable-aof-after-use.patch
# PATCH-FIX-UPSTREAM lazyfree-test-explicit-stream-ids.patch mpluskal@suse.com -- lazyfree stream test measures how fast the builder is, not lazyfree, https://github.com/redis/redis/pull/15585
Patch5:         lazyfree-test-explicit-stream-ids.patch
BuildRequires:  gcc-c++
BuildRequires:  python3
BuildRequires:  pkgconfig
BuildRequires:  pkgconfig(jemalloc)
BuildRequires:  pkgconfig(libsystemd)
BuildRequires:  pkgconfig(openssl)
BuildRequires:  pkgconfig(systemd)
%if "%{flavor}" == ""
BuildRequires:  sysuser-shadow
BuildRequires:  sysuser-tools
Recommends:     logrotate
Conflicts:      valkey-compat-%{origname}
%sysusers_requires
%endif
%if "%{flavor}" == "test"
BuildRequires:  procps
# there is no tcl-tls package yet, which is said to be needed for testing tls support
BuildRequires:  tcl
# Upstream does not support s390x -- "Add s390x support" (redis/redis#3359) has
# been open since 2024 -- and the suite finds it: hash field TTLs do not survive
# an RDB reload there (HPEXPIRETIME comes back as -2, the field is gone) and a
# cluster test aborts the whole run with an unhandled MOVED. Those are real
# big-endian bugs upstream, not something this package can patch around, and a
# permanently red flavour is worth less than one that is not built at all.
ExcludeArch:    s390x
%endif
%if "%{flavor}" == "modules"
# The module builds drive themselves through upstream's "readies" harness:
# cmake for redisbloom/redisearch/redistimeseries, cargo for the Rust parts of
# redisearch and redisjson, and a python3 that can run "pip --version" --
# readies' getpy3 probes for pip, not just for the interpreter. redistimeseries
# additionally builds a bundled libevent from a git checkout with no configure
# script in it, hence the autotools.
BuildRequires:  autoconf
BuildRequires:  automake
BuildRequires:  cargo
BuildRequires:  cmake
BuildRequires:  libboost_headers-devel
# redisearch's and redisjson's vendored redis-module crate runs bindgen at
# build time to generate the RedisModule_* FFI bindings, and bindgen dlopen()s
# libclang.so.* itself.
BuildRequires:  clang-devel
BuildRequires:  libtool
BuildRequires:  python3-pip
BuildRequires:  python3-setuptools
BuildRequires:  rust
# for unpacking the vendor tarballs in %%prep
BuildRequires:  zstd
# The modules are 64-bit x86/ARM only, and that is upstream's own limit rather
# than a packaging one: RedisBloom and RedisTimeSeries abort outright with
# "only supports 64-bit architectures (x64, arm64v8)", and redisjson's vendored
# redis-module declares the defrag cursor as u32 where a 64-bit build needs u64.
# modules/common.mk maps only x86_64, i386/i686 and aarch64/arm64 to a build
# variant anyway; everywhere else ARCH comes out empty and its tab-indented
# $(error) is read as a recipe, so make reports the unhelpful "recipe commences
# before first target" instead of naming the architecture.
ExclusiveArch:  x86_64 aarch64
%endif

%description
%{origname} is an advanced key-value store. It is similar to memcached but the dataset
is not volatile, and values can be strings, exactly like in memcached,
but also lists, sets, and ordered sets. All this data types can be manipulated
with atomic operations to push/pop elements, add/remove elements, perform server
side union, intersection, difference between sets, and so forth. Redis supports
different kind of sorting abilities.

%if "%{flavor}" == "modules"
%package -n %{origname}-bloom
Summary:        Probabilistic data structures for Redis
Requires:       %{origname} = %{version}
Provides:       redisbloom = %{version}
%requires_file %{_libdir}/libclang.so

%description -n %{origname}-bloom
RedisBloom adds Bloom filter, Cuckoo filter, count-min sketch, t-digest and
top-k data structures to Redis.

Load it by adding the following to a configuration file below
%{_conf_dir}/includes:

    loadmodule %{_module_dir}/redisbloom.so

%package -n %{origname}-search
Summary:        Query, secondary index and full-text search for Redis
Requires:       %{origname} = %{version}
Provides:       redisearch = %{version}
%requires_file %{_libdir}/libclang.so

%description -n %{origname}-search
RediSearch turns Redis into a document database with a secondary index,
full-text search, vector similarity search and aggregation.

Load it by adding the following to a configuration file below
%{_conf_dir}/includes:

    loadmodule %{_module_dir}/redisearch.so

%package -n %{origname}-json
Summary:        JSON data type for Redis
Requires:       %{origname} = %{version}
Provides:       redisjson = %{version}
%requires_file %{_libdir}/libclang.so

%description -n %{origname}-json
RedisJSON adds a native JSON data type to Redis, letting JSON documents be
stored, updated and queried down to individual paths.

Load it by adding the following to a configuration file below
%{_conf_dir}/includes:

    loadmodule %{_module_dir}/rejson.so

%package -n %{origname}-timeseries
Summary:        Time series data type for Redis
Requires:       %{origname} = %{version}
Provides:       redistimeseries = %{version}
%requires_file %{_libdir}/libclang.so

%description -n %{origname}-timeseries
RedisTimeSeries adds a time series data type to Redis, with downsampling,
compaction rules, aggregation and secondary indexing by label.

Load it by adding the following to a configuration file below
%{_conf_dir}/includes:

    loadmodule %{_module_dir}/redistimeseries.so
%endif

%prep
echo "`grep -F %{origname}-%{version}.tar.gz %{SOURCE10} | cut -d' ' -f4`  %{SOURCE0}" | sha256sum -c
%autosetup -p1 -n %{origname}-%{version}
%if "%{flavor}" == "modules"
# Vendored crates for the two Rust modules. Both tarballs already carry the
# path they belong at, plus a .cargo/config.toml that merges upstream's own
# settings with the vendor redirect, so they unpack straight over the tree.
tar -xf %{SOURCE20}
tar -xf %{SOURCE21}
# redisearch downloads a boost release from github when the directory it
# expects boost in does not exist. Everything it uses of boost is header-only
# (geometry, optional, smart_ptr, unordered, uuid, version) and the path ends
# up as a plain -I, so pointing it at the system headers both keeps the build
# offline and avoids carrying a second copy of boost.
ln -s %{_includedir} modules/redisearch/src/.install/boost
# redisjson builds with --all-targets, which includes the test executables.
# Those reference the RedisModule_* API that only exists inside the server that
# dlopen()s the module, so they cannot link -- and the module itself, a cdylib,
# does not need them. Build the libraries only.
sed -i 's/ --all-targets//' modules/redisjson/src/Makefile
# Both Rust modules split their own debug info out into a .so.debug sibling and
# leave a .gnu_debuglink behind. That sibling is not something a package should
# ship, and the debuglink makes rpm's find-debuginfo skip the file entirely, so
# the module ends up with no debuginfo package, a dangling debuglink and its
# symbol table still in place. Leave the binaries alone and let rpm do it.
sed -i '/extract_symbols_safe.sh/d' modules/redisjson/src/Makefile
sed -i 's/^\( *\)if(CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo" AND NOT APPLE)$/\1if(FALSE) # debug symbols are extracted by rpm, see redis.spec/' \
        modules/redisearch/src/CMakeLists.txt
tar -xf %{SOURCE22}
%endif

%build
export HOST=OBS # for reproducible builds
%if "%{flavor}" == "modules"
export CARGO_NET_OFFLINE=true
# redisearch refuses to build unless it recognises the distribution, and its
# checker only knows dpkg, rpm-on-rhel, apk and tdnf systems. The dependencies
# it looks for are BuildRequires above, so skipping its check is safe -- this
# is upstream's own documented escape hatch.
export IGNORE_MISSING_DEPS=1
# redisearch bundles VectorSimilarity, which by default builds Intel's
# ScalableVectorSearch backend. That pulls eve, fmt, spdlog, tomlplusplus and
# robin-map from git at configure time, and its SVS_SHARED_LIB path downloads a
# pre-compiled shared library from Intel -- none of which belongs in a
# distribution package. Without it VectorSimilarity uses its own HNSW and flat
# indexes, so vector search still works. redisearch's build.sh appends to
# CMAKE_ARGS without initialising it, so the environment is the way in.
# FETCHCONTENT_SOURCE_DIR_* is cmake's own way of satisfying a FetchContent
# dependency from a local tree instead of the network; cpu_features is the only
# one left once SVS is off.
export CMAKE_ARGS="-DUSE_SVS=OFF -DFETCHCONTENT_SOURCE_DIR_CPU_FEATURES=$(pwd)/cpu_features-0.10.1"
# modules.yaml asks for LTO on redisearch, which there means clang driving
# ld.bfd through LLVMgold.so -- a plugin openSUSE's clang does not ship, so
# every compiler probe fails before a line is compiled. common.mk applies the
# manifest defaults with ?=, so a value from the environment wins.
export LTO=0
# -Wno-error=return-type: the redismodule.h in the vendored redismodule-rs -- a
#   git dependency of redisjson -- has a function that falls off the end, and
#   cc-rs picks CFLAGS up from the environment, so -Werror=return-type out of
#   %%{optflags} turns that into a build failure.
# -fPIC: redistimeseries links a bundled libevent it builds itself into its
#   shared module, and libevent's own build produces a non-PIC static library,
#   which on aarch64 is a hard "dangerous relocation" link error.
# Everything else %%{optflags} asks for is kept.
CFLAGS="%{optflags} -Wno-error=return-type -fPIC"
export CFLAGS
export CXXFLAGS="${CFLAGS}"
# Upstream's "build" wrapper always builds the server first and only then the
# selected modules; the server binaries this produces are thrown away below,
# the redis package proper is built by the "" flavour. The modules are named
# one by one rather than via the "all" selector because "all" is also a real
# target in the top-level Makefile and would be built as a second goal.
%make_build build redisbloom redisearch redisjson redistimeseries \
        CFLAGS="${CFLAGS}"
%else
# Build the server only. Since 8.x upstream vendors redisbloom, redisearch,
# redisjson and redistimeseries into modules/ and the default target builds
# them, turning any module failure into a hard error. "build core" selects
# just the server; the modules are the "modules" flavour's job.
%make_build build core CFLAGS="%{optflags}" \
        BUILD_WITH_SYSTEMD=yes \
        BUILD_TLS=yes
%endif
%if "%{flavor}" == ""
%sysusers_generate_pre %{SOURCE9} %{origname}
%endif

%install
%if "%{flavor}" == "modules"
install -Dpm0755 modules/redisbloom/redisbloom.so \
        %{buildroot}%{_module_dir}/redisbloom.so
install -Dpm0755 modules/redisearch/redisearch.so \
        %{buildroot}%{_module_dir}/redisearch.so
install -Dpm0755 modules/redisjson/rejson.so \
        %{buildroot}%{_module_dir}/rejson.so
install -Dpm0755 modules/redistimeseries/redistimeseries.so \
        %{buildroot}%{_module_dir}/redistimeseries.so
%endif

%if "%{flavor}" == ""
install -pm0750 -d \
  %{buildroot}%{_sbindir} \
  %{buildroot}%{_log_dir} \
  %{buildroot}%{_data_dir} \
  %{buildroot}%{_conf_dir} \
  %{buildroot}%{_log_dir}/default \
  %{buildroot}%{_data_dir}/default

install -Dpm0755 src/%{origname}-benchmark %{buildroot}%{_bindir}/%{origname}-benchmark
install -Dpm0755 src/%{origname}-cli       %{buildroot}%{_bindir}/%{origname}-cli

install -Dpm0755 src/%{origname}-server    %{buildroot}%{_sbindir}/%{origname}-server

ln -sfv ../sbin/redis-server            %{buildroot}%{_bindir}/%{origname}-check-aof
ln -sfv ../sbin/redis-server            %{buildroot}%{_bindir}/%{origname}-check-rdb
ln -sfv ../sbin/redis-server            %{buildroot}%{_sbindir}/%{origname}-check-aof
ln -sfv ../sbin/redis-server            %{buildroot}%{_sbindir}/%{origname}-check-rdb
ln -sfv ../sbin/redis-server            %{buildroot}%{_sbindir}/%{origname}-sentinel

install -Dpm0640 redis.conf             %{buildroot}%{_conf_dir}/includes/redis.defaults.conf
install -Dpm0640 sentinel.conf          %{buildroot}%{_conf_dir}/includes/sentinel.defaults.conf

install -Dpm0640 redis.default.conf     %{buildroot}%{_conf_dir}/redis.default.conf.template
install -Dpm0660 sentinel.default.conf  %{buildroot}%{_conf_dir}/sentinel.default.conf.template

# some sysctl stuff
install -Dpm0644 %{SOURCE6} %{buildroot}%{_prefix}/lib/sysctl.d/00-%{origname}.conf
mkdir -p %{buildroot}%{_distconfdir}/logrotate.d
install -Dpm0644 %{SOURCE1} %{buildroot}%{_distconfdir}/logrotate.d/%{origname}
install -Dpm0644 %{SOURCE2} %{buildroot}%{_unitdir}/%{origname}.target
install -Dpm0644 %{SOURCE3} %{buildroot}%{_unitdir}/%{origname}@.service
install -Dpm0644 %{SOURCE4} %{buildroot}%{_tmpfilesdir}/%{origname}.conf
install -Dpm0644 %{SOURCE7} %{buildroot}%{_unitdir}/%{origname}-sentinel@.service
install -Dpm0644 %{SOURCE8} %{buildroot}%{_unitdir}/%{origname}-sentinel.target

ln -s %{_sbindir}/service %{buildroot}%{_sbindir}/rc%{origname}
cp %{SOURCE5} README.SUSE

mkdir -p %{buildroot}%{_sysusersdir}
install -pm0644 %{SOURCE9} %{buildroot}%{_sysusersdir}/
%endif

%check
%if "%{flavor}" == "test"
# The suite used to be run with "|| true" here because it kept failing to start
# a server with 'child process exited abnormally'. That turns out to be servers
# leaked by an earlier run of the suite still sitting on ports in the range the
# test clients are handed; in a fresh build root there are none and the suite
# passes. So let a failure be a failure -- this flavour ships nothing, so a
# red test run blocks no rebuild.
# Cap the run: a test client that wedges rather than failing would otherwise sit
# on the worker until the global build timeout, and "make -C src test" gives no
# way to pass the suite's own --timeout through to runtest. The suite needs
# about 25 minutes here, so two hours is a generous ceiling that still fails in
# bounded time; -k makes sure a client ignoring SIGTERM is killed.
#
# runtest is called directly instead of through "make test": src/Makefile's test
# target hardcodes a bare "./runtest", and the skip options below have to reach
# it. That target also depends on the helper modules the moduleapi tests
# dlopen(); %%build's "build core" already produces them, so the line below is
# only a cheap guarantee that they exist however %%build is later changed.
# Variable assignments need to match in all make invocations, otherwise it might recomplie. See https://github.com/redis/redis/issues/7337
%make_build -C src module_tests CFLAGS="%{optflags}" BUILD_WITH_SYSTEMD=yes BUILD_TLS=yes
# --no-latency is upstream's own switch for the assertions that bound how long
# an operation took (LATENCY HISTORY/LATEST, the active-defrag max_latency
# ceilings). Those measure the builder's load rather than redis, and a shared
# OBS worker misses them on the slower architectures.
#
# Two more tests bound wall-clock time with no switch to turn them off, so they
# are named here. --skipfile takes one test name per line, matched literally.
cat > obs-skiptests <<'EOF'
BZPOPMIN unblock but the key is expired and then block again - reprocessing command
XREADGROUP CLAIM block times out with no claimable messages
EOF
%ifarch ppc64le
# "defrag didn't stop" -- the active-defrag cycle does not converge inside the
# suite's wait on ppc64le. Long-standing and not specific to this version:
# boo#1247364 records the same failure against redis 6.0.14 and 7.0.8 there in
# 2025. It is a wait_for_condition timeout, so --no-latency does not cover it.
cat >> obs-skiptests <<'EOF'
Active defrag can't be triggered during replicaof database flush. See issue #14267
EOF
%endif
%ifarch %{ix86}
# "defrag didn't stop or failed to achieve expected frag ratio" -- on 32-bit x86
# the fragmentation target is actually met (1.06 against the 1.1 asked for); it
# is the other half of the condition that never comes true. Residual small-bin
# waste settles around 6% / 1.6MB, just above both the active-defrag-threshold-
# lower (5) and active-defrag-ignore-bytes (1500kb) the test itself sets, so
# activeDefragCycle never reaches its stop condition and the 50s wait expires.
# A three percent margin, so it is not something --no-latency covers. Entries
# beginning with '/' are regexps, which catches both ": cluster" and
# ": standalone".
cat >> obs-skiptests <<'EOF'
/^Active defrag IDMP streams:
EOF
%endif
# tests/integration/logging.tcl and tests/unit/moduleapi/crash.tcl assert on the
# contents of redis' own crash report -- the stack trace, the frame for the
# command that crashed, one "STACK TRACE" block per thread. Upstream gates them
# on system_backtrace_supported (tests/support/util.tcl), which only asks
# whether this is Linux with a non-musl libc and never looks at the
# architecture, so they also run where the crash reporter cannot deliver what
# they expect. x86_64 and aarch64 do, and keep running them.
# Unquoted on purpose below: the value is meant to split into words.
%ifarch x86_64 aarch64
skipunits=
%else
skipunits="--skipunit integration/logging --skipunit unit/moduleapi/crash"
%endif
# runtest defaults to 16 parallel clients, each starting several servers. On an
# OBS worker that oversubscribes the machine badly -- a run whose per-unit times
# sum to about 2900s finishes in 600s of wall clock -- and the tests that then
# fail are the ones with a fixed deadline: a cluster MEET handshake has to
# complete inside cluster-node-timeout or the node is dropped, an AOF child has
# to be reaped before a shutdown, and so on. Each architecture lost a different
# one of these, which is the signature of contention rather than of a bug in any
# of them. Upstream has a guard for exactly this (is_a_slow_computer, which
# drops to a single client) but it times a Tcl loop and so cannot see load.
# Four clients keeps the run comfortably inside the timeout above.
timeout -k 60 7200 \
./runtest --no-latency --clients 4 --skipfile obs-skiptests ${skipunits}
%endif
%if "%{flavor}" == "modules"
# A module that did not finish linking still produces a file, so check that
# each one actually exports the entry point the server dlsym()s.
for so in %{buildroot}%{_module_dir}/*.so; do
    nm -D --defined-only "${so}" | grep -qw RedisModule_OnLoad ||
        { echo "error: ${so} does not export RedisModule_OnLoad" >&2; exit 1; }
done
%endif
%if "%{flavor}" == ""
src/%{origname}-server --version
src/%{origname}-cli --version
%endif

%if "%{flavor}" == ""
%pre -f %{origname}.pre
%service_add_pre %{origname}.target %{origname}@.service %{origname}-sentinel.target %{origname}-sentinel@.service
# Prepare for migration to /usr/etc; save any old .rpmsave
for i in logrotate.d/%{origname} ; do
   test -f %{_sysconfdir}/${i}.rpmsave && mv -v %{_sysconfdir}/${i}.rpmsave %{_sysconfdir}/${i}.rpmsave.old ||:
done

%posttrans
# Migration to /usr/etc, restore just created .rpmsave
for i in logrotate.d/%{origname} ; do
   test -f %{_sysconfdir}/${i}.rpmsave && mv -v %{_sysconfdir}/${i}.rpmsave %{_sysconfdir}/${i} ||:
done

%post
%tmpfiles_create %{_tmpfilesdir}/%{origname}.conf
%service_add_post %{origname}.target %{origname}@.service %{origname}-sentinel.target %{origname}-sentinel@.service
echo "See %{_docdir}/%{origname}/README.SUSE to continue"

%preun
%service_del_preun %{origname}.target %{origname}@.service %{origname}-sentinel.target %{origname}-sentinel@.service

%postun
%service_del_postun %{origname}.target %{origname}@.service %{origname}-sentinel.target %{origname}-sentinel@.service

%files
%license LICENSE.txt
# redis-full.conf is generated only by the module build (it carries the
# loadmodule lines) and would reference modules this package does not ship
%doc 00-RELEASENOTES BUGS REDISCONTRIBUTIONS.txt *.md
%{_distconfdir}/logrotate.d/%{origname}
%{_prefix}/lib/sysctl.d/00-%{origname}.conf
%{_bindir}/%{origname}-*
%{_sbindir}/%{origname}-*
%{_sbindir}/rc%{origname}
%{_tmpfilesdir}/%{origname}.conf
%{_sysusersdir}/%{origname}-user.conf
%{_unitdir}/%{origname}@.service
%{_unitdir}/%{origname}.target
%{_unitdir}/%{origname}-sentinel@.service
%{_unitdir}/%{origname}-sentinel.target
%doc README.SUSE
%config(noreplace) %attr(-,root,%{origname}) %{_conf_dir}/
%dir %attr(0750,%{origname},%{origname}) %{_data_dir}
%dir %attr(0750,%{origname},%{origname}) %{_data_dir}/default
%dir %attr(0750,%{origname},%{origname}) %{_log_dir}
%ghost %dir %attr(0755,%{origname},%{origname}) /run/%{origname}
%endif

%if "%{flavor}" == "modules"
%files -n %{origname}-bloom
%license modules/redisbloom/src/LICENSE.txt
%doc modules/redisbloom/src/README.md
%dir %{_libdir}/%{origname}
%dir %{_module_dir}
%{_module_dir}/redisbloom.so

%files -n %{origname}-search
%license modules/redisearch/src/LICENSE.txt
%doc modules/redisearch/src/README.md
%dir %{_libdir}/%{origname}
%dir %{_module_dir}
%{_module_dir}/redisearch.so

%files -n %{origname}-json
%license modules/redisjson/src/LICENSE.txt
%doc modules/redisjson/src/README.md
%dir %{_libdir}/%{origname}
%dir %{_module_dir}
%{_module_dir}/rejson.so

%files -n %{origname}-timeseries
%license modules/redistimeseries/src/LICENSE.txt
%doc modules/redistimeseries/src/README.md
%dir %{_libdir}/%{origname}
%dir %{_module_dir}
%{_module_dir}/redistimeseries.so
%endif

%changelog
