#
# spec file for package perl-Class-MethodMaker
#
# Copyright (c) 2015 SUSE LINUX GmbH, Nuernberg, Germany.
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Please submit bugfixes or comments via http://bugs.opensuse.org/
#


Name:           perl-Class-MethodMaker
Version:        2.24
Release:        0
%define cpan_name Class-MethodMaker
Summary:        Create generic methods for OO Perl
License:        Artistic-1.0 or GPL-1.0+
Group:          Development/Libraries/Perl
Url:            http://search.cpan.org/dist/Class-MethodMaker/
Source:         http://www.cpan.org/authors/id/S/SC/SCHWIGON/class-methodmaker/%{cpan_name}-%{version}.tar.gz
# PATCH-FIX-UPSTREAM https://rt.cpan.org/Public/Bug/Display.html?id=122339
Patch0:         reproducible.patch
BuildRoot:      %{_tmppath}/%{name}-%{version}-build
BuildRequires:  perl
BuildRequires:  perl-macros
%{perl_requires}

%description
This module solves the problem of having to continually write accessor
methods for your objects that perform standard tasks.

The argument to 'use' is an *arrayref*, as pairs whose "keys" are the names
of types of generic methods generated by MethodMaker and whose "values"
tell method maker what methods to make.

To override any generated methods, it is sufficient to ensure that the
overriding method is defined when Class::MethodMaker is called. Note that
the 'use' keyword introduces a 'BEGIN' block, so you may need to define (or
at least declare) your overriding method in a 'BEGIN' block.

%prep
%setup -q -n %{cpan_name}-%{version}
%patch0 -p1
find . -type f -print0 | xargs -0 chmod 644

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="%{optflags}"
%{__make} %{?_smp_mflags}

%check
%{__make} test

%install
%perl_make_install
%perl_process_packlist
%perl_gen_filelist

%files -f %{name}.files
%defattr(-,root,root,755)
%doc Changes examples README TODO

%changelog
