.TH SAXON9Q "1" "December 2012" "9.4" "User Commands"
.SH NAME
saxon9q \- Saxon XQuery processor
.SH SYNOPSIS
.B saxon9q
[\fIoptions\fR] \fI-q:queryfile \fR[\fIparam=value\fR...]
.SH DESCRIPTION
saxon9q runs an XQuery query contained in a file.
.SH OPTIONS
See:
.TP
\fIhttp://www.saxonica.com/documentation/using-xquery/commandline.xml\fR
.TP
for command line usage.
.SH "SEE ALSO"
.BR saxon9 (1) .
.SH AUTHOR
Michael H. Kay <mike@saxonica.com>
