## Copy this file to /etc/ to make changes in the configuration

## enable (set ot 1) or disable (0) the transactional wrapper
## default is disabled
ENABLE_TRANSACTIONAL_WRAPPER=1


## action to perform after update
## apply for calling "transactional-update apply"
## reboot for immediate rebooting after the operation
## soft-reboot for immediate soft-rebooting after the operation
## kexec for immediate rebooting after the operation via exec
## info for only informing the user to reboot
## default is "info"
ACTION="info"
