#
# spec file for package python-partial-json-parser
#
# Copyright (c) 2026 SUSE LLC
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Please submit bugfixes or comments via https://bugs.opensuse.org/
#


%{?sle15_python_module_pythons}
Name:           python-partial-json-parser
Version:        0.2.1.1.post7
Release:        0
Summary:        Parse partial JSON generated by LLM
License:        MIT
URL:            https://github.com/promplate/partial-json-parser
Source:         https://files.pythonhosted.org/packages/source/p/partial_json_parser/partial_json_parser-%{version}.tar.gz
BuildRequires:  %{python_module pdm-backend}
BuildRequires:  %{python_module pip}
BuildRequires:  fdupes
BuildRequires:  python-rpm-macros
BuildArch:      noarch
%python_subpackages

%description
Parse partial and incomplete JSON strings, such as the streamed output of
a large language model (LLM). Before the final token of a response is
received the JSON is broken and cannot be decoded with a normal parser;
partial-json-parser completes the fragment so the partial structure can be
used while streaming. It is implemented purely in Python and is
zero-dependency.

%prep
%autosetup -p1 -n partial_json_parser-%{version}

%build
%pyproject_wheel

%install
%pyproject_install
# Drop the optional "playground" console script: it pulls the rich extra
# and is not part of the library API. Remove the installed entry point.
rm %{buildroot}%{_bindir}/json-playground
%python_expand rm %{buildroot}%{$python_sitelib}/partial_json_parser-%{version}.dist-info/entry_points.txt
%python_expand %fdupes %{buildroot}%{$python_sitelib}

# Upstream ships no tests in the sdist (pyproject excludes the tests dir),
# so there is nothing to run here; smoke-test the import and completion of a
# truncated JSON array instead. The fragment is intentionally an array, not an
# object: an unbalanced curly brace inside python_expand confuses the rpm macro
# brace counter and swallows the following files expansion.
%check
%python_expand PYTHONPATH=%{buildroot}%{$python_sitelib} $python -B -c "import partial_json_parser; assert partial_json_parser.loads('[1, 2') == [1, 2]"

%files %{python_files}
%license LICENSE
%doc README.md
%{python_sitelib}/partial_json_parser
%{python_sitelib}/partial_json_parser-%{version}.dist-info

%changelog
