#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          cmsd
# Required-Start:    $syslog $remote_fs $network
# Required-Stop:     $syslog $remote_fs $network
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: cmsd daemon providing xrootd-server
# Description:       cmsd daemon providing xrootd-server
### END INIT INFO

CMSD_BIN=/usr/bin/cmsd
test -x $XROOT_BIN || { echo "$CMSD_BIN not installed"; 
        if [ "$1" = "stop" ]; then exit 0;
        else exit 5; fi; }

CMSD_CONFIG=/etc/sysconfig/xrootd
test -r $CMSD_CONFIG || { echo "$CMSD_CONFIG not existing";
        if [ "$1" = "stop" ]; then exit 0;
        else exit 6; fi; }

CMSD_FUNCTIONS=/etc/xrootd/xrootd.functions
test -r $CMSD_FUNCTIONS || { echo "$CMSD_FUNCTIONS not existing";
        if [ "$1" = "stop" ]; then exit 0;
        else exit 6; fi; }

. $CMSD_FUNCTIONS
. $CMSD_CONFIG
. /etc/rc.status
rc_reset

case "$1" in
    start)
        echo -n "Starting CMSD "
        /sbin/startproc $CMSD_BIN
        rc_status -v
        ;;
    stop)
        echo -n "Shutting down CMSD "
        /sbin/killproc $CMSD_BIN
        rc_status -v
        ;;
    try-restart|condrestart)
        if test "$1" = "condrestart"; then
                echo "${attn} Use try-restart ${done}(LSB)${attn} rather than condrestart ${warn}(RH)${norm}"
        fi
        $0 status
        if test $? = 0; then
                $0 restart
        else
                rc_reset        # Not running is not a failure.
        fi
        rc_status
        ;;
    restart)
        $0 stop
        $0 start
        rc_status
        ;;
    force-reload)
        echo -n "Reload service CMSD "
        /sbin/killproc -HUP $CMSD_BIN
        rc_status -v

        ;;
    reload)
        echo -n "Reload service CMSD "
        /sbin/killproc -HUP $CMSD_BIN
        rc_status -v
        ;;
    status)
        echo -n "Checking for service CMSD "
        /sbin/checkproc $CMSD_BIN
        rc_status -v
        ;;
    *)
        echo "Usage: $0 {start|stop|status|try-restart|restart|force-reload|reload|probe}"
        exit 1
        ;;
esac
rc_exit
