#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          frm_purged
# Required-Start:    $syslog $remote_fs $network
# Required-Stop:     $syslog $remote_fs $network
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: frm_purged daemon providing xrootd-server
# Description:       frm_purged daemon providing xrootd-server
### END INIT INFO

FRMPURGED_BIN=/usr/bin/frm_purged
test -x $XROOT_BIN || { echo "$FRMPURGED_BIN not installed"; 
        if [ "$1" = "stop" ]; then exit 0;
        else exit 5; fi; }

FRMPURGED_CONFIG=/etc/sysconfig/xrootd
test -r $FRMPURGED_CONFIG || { echo "$FRMPURGED_CONFIG not existing";
        if [ "$1" = "stop" ]; then exit 0;
        else exit 6; fi; }

FRMPURGED_FUNCTIONS=/etc/xrootd/xrootd.functions
test -r $FRMPURGED_FUNCTIONS || { echo "$FRMPURGED_FUNCTIONS not existing";
        if [ "$1" = "stop" ]; then exit 0;
        else exit 6; fi; }

. $FRMPURGED_FUNCTIONS
. $FRMPURGED_CONFIG
. /etc/rc.status
rc_reset

case "$1" in
    start)
        echo -n "Starting FRMPURGED "
        /sbin/startproc $FRMPURGED_BIN
        rc_status -v
        ;;
    stop)
        echo -n "Shutting down FRMPURGED "
        /sbin/killproc $FRMPURGED_BIN
        rc_status -v
        ;;
    try-restart|condrestart)
        if test "$1" = "condrestart"; then
                echo "${attn} Use try-restart ${done}(LSB)${attn} rather than condrestart ${warn}(RH)${norm}"
        fi
        $0 status
        if test $? = 0; then
                $0 restart
        else
                rc_reset        # Not running is not a failure.
        fi
        rc_status
        ;;
    restart)
        $0 stop
        $0 start
        rc_status
        ;;
    force-reload)
        echo -n "Reload service FRMPURGED "
        /sbin/killproc -HUP $FRMPURGED_BIN
        rc_status -v

        ;;
    reload)
        echo -n "Reload service FRMPURGED "
        /sbin/killproc -HUP $FRMPURGED_BIN
        rc_status -v
        ;;
    status)
        echo -n "Checking for service FRMPURGED "
        /sbin/checkproc $FRMPURGED_BIN
        rc_status -v
        ;;
    *)
        echo "Usage: $0 {start|stop|status|try-restart|restart|force-reload|reload|probe}"
        exit 1
        ;;
esac
rc_exit
