#
# spec file for package findutils
#
# Copyright (c) 2020 SUSE LLC
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Please submit bugfixes or comments via https://bugs.opensuse.org/
#


Name:           findutils
URL:            http://www.gnu.org/software/findutils/
Version:        4.7.0
Release:        0
Summary:        The GNU versions of find utilities (find and xargs)
License:        GPL-3.0-or-later
Group:          Productivity/File utilities

# Upstream development:
# cgit-URL:	https://git.savannah.gnu.org/cgit/findutils.git/
# Git-Clone:	git://git.sv.gnu.org/findutils

# For upgrading the upstream version, increase the version number (above),
# then remove the old tarball and signature files and let OSC download
# those files of the new version:
#    osc rm findutils-*.tar.xz findutils-*.tar.xz.sig
#    osc service localrun download_files
#    osc addremove
# Then adjust the downstream patches (using quilt).
# Finally, add a changelog entry and commit:
#    osc vc
#    osc ci
Source0:        https://ftp.gnu.org/pub/gnu/%{name}/%{name}-%{version}.tar.xz
Source1:        https://ftp.gnu.org/gnu/%{name}/%{name}-%{version}.tar.xz.sig
Source2:        https://savannah.gnu.org/project/memberlist-gpgkeys.php?group=%{name}&download=1&file=./%{name}.keyring

# adds a new option -xautofs to find to not descend into directories on autofs file systems
Patch0:         findutils-xautofs.patch
Patch1:         disable-null-ptr-test.patch
Patch2:         findutils-gnulib-disable-test-float.patch

BuildRoot:      %{_tmppath}/%{name}-%{version}-build
# BuildRequire dejagnu for 'runtest' to execute all tests.
BuildRequires:  dejagnu
%if 0%{?suse_version} > 1100
BuildRequires:  libselinux-devel
%endif
BuildRequires:  makeinfo
Provides:       find = %{version}
Obsoletes:      find < %{version}
Requires(post):  %{install_info_prereq}
Requires(preun): %{install_info_prereq}

%description
The findutils package contains programs which will help you locate
files on your system.  The find utility searches through a hierarchy
of directories looking for files which match a certain set of criteria
(such as a file name pattern).  The xargs utility builds and executes
command lines from standard input arguments (usually lists of file
names generated by the find command).

You should install findutils because it includes tools that are very
useful for finding things on your system.


%lang_package

%prep
%setup -q
%patch0
%patch1 -p1

%ifarch ppc ppc64le
# Disable gnulib test 'test-float' temporarily as it fails on ppc and ppc64le.
%patch2
%endif

%build
%if 0%{?qemu_user_space_build}
# this is a workaround for a qemu-user bug, we hit. A qemu patch is being discussed, but for now ...
export DEFAULT_ARG_SIZE="(31u * 1024u)"
%endif
%configure \
  --libexecdir=%{_libdir}/find \
  --localstatedir=/var/lib

make %{?_smp_mflags}

%check
make check \
  || { cat tests/test-suite.log; exit 1; }

%install
make DESTDIR=%{buildroot} install

rm -f %{buildroot}%{_infodir}/find-maint*
%find_lang %{name}
#UsrMerge
mkdir -p %{buildroot}/bin
ln -sf %{_bindir}/find %{buildroot}/bin
#UsrMerge

rm %{buildroot}%{_bindir}/locate
rm %{buildroot}%{_bindir}/updatedb
rm -r %{buildroot}%{_libdir}/find
rm %{buildroot}%{_mandir}/man1/locate.1*
rm %{buildroot}%{_mandir}/man1/updatedb.1*
rm %{buildroot}%{_mandir}/man5/locatedb.5*

%post
%install_info --info-dir=%{_infodir} %{_infodir}/find.info.gz

%preun
%install_info_delete --info-dir=%{_infodir} %{_infodir}/find.info.gz

%files
%defattr(-,root,root,-)
%license COPYING
%doc AUTHORS NEWS README THANKS TODO
#UsrMerge
/bin/find
#UsrMerge
%{_bindir}/find
%{_bindir}/xargs
%doc %{_infodir}/find.info*.gz
%doc %{_mandir}/man1/find.1.gz
%doc %{_mandir}/man1/xargs.1.gz

%files lang -f %{name}.lang
%defattr(-,root,root,-)

%changelog
