d /var/lib/@PKG_NAME@/data @STATE_DIR_PERMS@ @STATE_DIR_OWNER@ @STATE_DIR_OWNER@
d /var/lib/@PKG_NAME@/logs @STATE_DIR_PERMS@ @STATE_DIR_OWNER@ @STATE_DIR_OWNER@
d /var/lib/@PKG_NAME@/tmp @STATE_DIR_PERMS@ @STATE_DIR_OWNER@ @STATE_DIR_OWNER@

