.TH "xfdashboard-settings" "1" "0.6.0" "Dmitriy A. Perlow aka DAP-DarkneSS" ""
.SH "NAME"
xfdashboard-settings is a part of xfdashboard that provides a GNOME shell dashboard like interface for use with Xfce desktop. It can be configured to run to any keyboard shortcut and when executed provides an overview of applications currently open enabling the user to switch between different applications. The search feature works like Xfce's app finder which makes it convenient to search for and start applications.
.br

http://xfdashboard.froevel.de
.br
.SH "SYNTAX"
xfdashboard-settings
.br
.SH "AUTHORS"
https://github.com/gmc-holle
.br
