libdhash1
libdhash-devel
	requires -libdhash-<targettype>
	requires "libdhash1-<targettype> = <version>"
libini_config8
libini_config-devel
	requires -libini_config-<targettype>
	requires "libini_config8-<targettype> = <version>"
