# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='dephell_changelogs',
    version='0.0.1',
    description='Find changelog for github repository, local dir, parse changelog',
    python_requires='>=3.5',
    project_urls={"homepage": "https://github.com/dephell/dephell_changelogs"},
    author='Gram (@orsinium)',
    author_email='gram@orsinium.dev',
    classifiers=[
        'Development Status :: 5 - Production/Stable', 'Environment :: Console',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3', 'Programming Language :: Python',
        'Topic :: Software Development :: Libraries :: Python Modules'
    ],
    packages=['dephell_changelogs'],
    package_dir={"": "."},
    package_data={},
    install_requires=['pytest', 'requests'],
    extras_require={"dev": ["pytest-xdist"]},
)
