#
# spec file for package patch
#
# Copyright (c) 2026 SUSE LLC
# Copyright (c) 2025 Andreas Stieger <Andreas.Stieger@gmx.de>
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Please submit bugfixes or comments via https://bugs.opensuse.org/
#


Name:           patch
Version:        2.8
Release:        0
Summary:        GNU patch
License:        GPL-3.0-or-later
Group:          Productivity/Text/Utilities
URL:            https://ftp.gnu.org/gnu/patch/
Source:         https://ftp.gnu.org/gnu/patch/%{name}-%{version}.tar.xz
Source2:        https://ftp.gnu.org/gnu/patch/%{name}-%{version}.tar.xz.sig
# https://savannah.gnu.org/people/viewgpg.php?user_id=15000
Source3:        patch.keyring
Patch14:        CVE-2019-20633.patch
Patch15:        CVE-2021-45261.patch
BuildRequires:  ed
# See bnc#662957. The fix for CVE-2010-4651 breaks the way interdiff was
# invoking patch, so interdiff had to be fixed too.
Conflicts:      patchutils < 0.3.2

%description
The GNU patch program is used to apply diffs between original and
changed files (generated by the diff command) to the original files.

%prep
%autosetup -p1

%build
%configure \
# https://lists.gnu.org/archive/html/bug-patch/2025-04/msg00002.html
#	--enable-gcc-warnings \
	%{nil}
%make_build

%check
%make_build check

%install
%make_install

%files
%doc AUTHORS NEWS README
%license COPYING
%{_bindir}/patch
%{_mandir}/man1/patch.1%{?ext_man}

%changelog
