(lambda (features)
  (flet ((enable (x) (pushnew x features))
         (disable (x) (setf features (remove x features))))
    (enable :sb-thread)
    (enable :sb-core-compression)
    (enable :sb-futex)
    (enable :sb-xref-for-internals)
    features))
