#
# spec file for package xkeycaps
#
# Copyright (c) 2014 SUSE LINUX Products GmbH, Nuernberg, Germany.
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Please submit bugfixes or comments via http://bugs.opensuse.org/
#


Name:           xkeycaps
BuildRequires:  imake
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(xaw7)
BuildRequires:  pkgconfig(xmu)
BuildRequires:  pkgconfig(xt)
Version:        2.46
Release:        0
Summary:        A graphical frontend for "xmodmap"
License:        MIT
Group:          System/X11/Utilities
Url:            http://www.jwz.org/xkeycaps/
Source:         xkeycaps-%{version}.tar.bz2
Patch0:         xkeycaps-%{version}.patch
Patch1:         xkeycaps-%{version}-Xmodmap.patch
Patch2:         xkeycaps-%{version}-Imake.patch
Patch3:         %{name}-%{version}_context-menu.patch
Patch4:         %{name}-%{version}-memory-leak.patch
BuildRoot:      %{_tmppath}/%{name}-%{version}-build
%define _xorg7libs %_lib
%define _xorg7libs32 lib
%define _xorg7bin bin
%define _xorg7_mandir %_mandir
%define _xorg7pixmaps include
%define _xorg7libshare share
%define _xorg7_xkb /usr/share/X11/xkb
%define _xorg7_termcap /usr/lib/X11/etc
%define _xorg7_serverincl /usr/include/xorg
%define _xorg7_fonts /usr/share/fonts
#%define _xorg7_config /usr/share/X11/config #use libshare macro
%define _xorg7_prefix /usr

%description
"xkeycaps" is a graphical front-end to "xmodmap". It opens a window
that looks like a keyboard. Moving the mouse over a key shows what
KeySyms and Modifier bits that key generates. Clicking on a key
simulates KeyPress/KeyRelease events on the window of your choice. It
is possible to change the KeySyms and Modifiers generated by a key
through a mouse-based interface. This program can also write an input
file for xmodmap to recreate your changes in future sessions.



Authors:
--------
    Jamie Zawinski <jwz@jzw.org>

%prep
%setup -q
%patch0
%patch1
%patch2
%patch3
%patch4

%build
xmkmf -a
touch XKeyCaps_ad.h
make %{?jobs:-j%jobs}

%install
make install DESTDIR=${RPM_BUILD_ROOT}
make install.man DESTDIR=${RPM_BUILD_ROOT}

%clean
rm -rf ${RPM_BUILD_ROOT}

%files
%defattr(-,root,root)
%doc  README defining.txt hierarchy.txt sgi-microsoft.txt
%doc %{_xorg7_mandir}/man1/xkeycaps.1x.gz
/usr/%{_xorg7bin}/xkeycaps

%changelog
