#!/usr/bin/perl -w
# zypper in perl-libwww-perl perl-LWP-Protocol-https perl-JSON-XS
use strict;
use LWP::UserAgent ();
use JSON::XS;

our $UA = LWP::UserAgent->new(
        parse_head=>0,
        timeout=>9,
        agent=>"bmwiedemann/perl-get-packages/0.02",
        keep_alive => 5);


sub process($)
{ my $url = shift;
    while($url) {
	my $response = $UA->request(HTTP::Request->new('GET', $url));
	my $json = $response->content;
	my $data = decode_json($json);
	for my $p (@{$data->{projects}}) {
	    print $p->{name},"\n";
	}
	$url = $data->{pagination}->{next};
    }
}
process("https://code.opensuse.org/api/0/projects?namespace=package&short=1&per_page=100");
