#!/bin/sh
pkg=$1
[ -n "$1" ] || exit 1
first=$(echo $pkg | cut -c1)
p=packages/$first/$pkg #FIXME lib*
test -d $p || exit 2
rm -rf $p
git rm $p
git commit -m "Drop $pkg submodule"
git subtree add -P $p https://code.opensuse.org/package/$pkg master
grep '"$pkg"' /home/opensuserabbit/dumprabbit.json | tail -1 | scripts/rabbithandle-single.py
(cd /data/openSUSE-test/$p/ && rm -rf $p && git pull )
cp -a /data/openSUSE-test/$p/.git $p/
