#!/usr/bin/perl -w
use strict;
{
my $pkg=shift;
die "usage: $0 PKGNAME" unless $pkg;
die "invalid pkg" if $pkg =~ m/[^a-zA-Z0-9._+-]/;

my @rsync=qw"rsync -a
  --max-size=999000k
  --exclude=DELETED
  --exclude=.osc
  --delete
  --delete-missing-args
  --delete-excluded";
system(@rsync, "/mounts/work/SRC/openSUSE\:Factory/$pkg", "in/");
die "rsync of $pkg failed" unless $? == 0;
my $first=lc(substr($pkg, 0, 1));
system(qw"rm -rf", glob("packages/$first*/$pkg"));
$ENV{PKG}=$pkg;
}
do("./scripts/mappkgs.pl");
