#!/usr/bin/perl -w
# bring one package in the monorepo working tree up to date with Factory
use strict;
use FindBin;
use lib $FindBin::Bin;
use pkglib;
my $pkg=shift;
die "usage: $0 PKGNAME" unless $pkg;
checkpkg($pkg);

my @rsync=qw"rsync -a
  --max-size=999000k
  --exclude=DELETED
  --exclude=.osc
  --delete
  --delete-missing-args
  --delete-excluded";
system(@rsync, ($ENV{FACTORY} // "/mounts/work/SRC/openSUSE:Factory")."/$pkg", "in/");
die "rsync of $pkg failed" unless $? == 0;
$ENV{PKG}=$pkg;
system("$FindBin::Bin/mappkgs.pl", "in", "packages") == 0 or die "mappkgs failed for $pkg";
my $dir = pkgdir($pkg);
die "$dir/.git exists - package repos live in refs/pkg/, see pkgimport" if -e "$dir/.git";
# stage adds, changes and deletions
if(-d $dir) {
  git_ok("add", "-A", "--", $dir) or die "git add $dir failed";
} else {
  git_ok("rm", "-r", "-q", "--cached", "--ignore-unmatch", "--", $dir) or die "git rm $dir failed";
}
