#!/bin/sh
rsync="rsync -a \
  --max-size=999000k \
  --exclude=DELETED \
  --exclude=.osc \
  --delete \
  --delete-excluded"
$rsync /mounts/work/SRC/openSUSE\:Factory/ in/
p="openSUSE:Factory/_project"
test -e $p || osc co "$p"
osc up "$p"
$rsync "./$p/" in/_project/
mkdir -p ~/.cache
rm -rf packages
scripts/mappkgs.pl in packages
git add -f packages/*
git commit -a -m "update $(date -u +"%Y-%m-%d %H:%M")"
git push
