#
# Copyright (c) 2018-2026 SUSE LINUX GmbH, Nuernberg, Germany.
# All rights reserved.
#

# load pkey modules at boot time
uvdevice
pkey
pkey_cca
pkey_ep11
pkey_pckmo
pkey_uv
paes_s390
phmac_s390
zcrypt
zcrypt_cex4
