.TH CURAENGINE "1" "DATE" "CuraEngine VERSION" "User Commands"
.SH NAME
CuraEngine \- manual page for CuraEngine VERSION
.SH SYNOPSIS
.B CuraEngine 
[\fIOPTION\fR]... \fI-o OUTPUT \fR\fIMODEL\fR...
.SH DESCRIPTION
The CuraEngine is a C++ console application for 3D printing GCode
generation. It has been made as a better and faster alternative to the old
Skeinforge engine.
.TP
Example: CuraEngine -o <output.gcode> <model.stl>
.TP
\fB\-h\fR
Help
.TP
\fB\-v\fR
Version information
.TP
\fB\-s\fR
Settings key value
.TP
\fB\-m\fR
Size
.PP
