.TH "geos-config" "1" "October 25, 2004" "geos-config" "User Commands"
.SH "NAME"
geos\-config \- returns information about installed GEOS libraries and binaries
.SH "SYNOPSIS"
.PP 
.B geos\-config
[OPTIONS]
.SH "DESCRIPTION"
.PP 
The \fIgeos\-config\fP shell script displays configuration information for installed GEOS libraries and binaries. 

.SH "OPTIONS"
.TP 
\fB\-\-prefix\fR
print the prefix used by geos
.TP 
\fB\-\-version\fR
print the GEOS version
.TP 
\fB\-\-libs\fR
print the linker flags that are necessary to link to GEOS
.TP 
\fB\-\-cflags\fR
print the compiler flags that are necessary to compile a
plug\-in
.TP 
\fB\-\-includes\fR
show location of C++ header files
.TP 
\fB\-\-jtsport\fR
show the version of the Java Topology Suite this version of GEOS was ported from
