# vim: set sw=4 ts=4 et nu:
#
# spec file for package poezio
#
# Copyright (c) 2022 SUSE LLC
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Please submit bugfixes or comments via https://bugs.opensuse.org/
#


Name:           poezio
Version:        0.14
Release:        0
Summary:        XMPP Client for the Console
License:        MIT
Group:          Productivity/Networking/Other
URL:            https://poez.io/en/
Source:         https://lab.louiz.org/poezio/poezio/-/archive/v%{version}/poezio-v%{version}.tar.gz
# PATCH-FIX-OPENSUSE - remove shebangs -- sleep_walker@opensuse.org
Patch0:         poezio-remove_shebang.patch
BuildRequires:  fdupes
BuildRequires:  hicolor-icon-theme
BuildRequires:  make
BuildRequires:  python-rpm-macros
BuildRequires:  python3-curses
BuildRequires:  python3-devel
BuildRequires:  python3-setuptools
BuildRequires:  update-desktop-files
Requires:       python3-aiodns
Requires:       python3-curses
Requires:       python3-pyasn1-modules
Requires:       python3-setuptools
Requires:       python3-slixmpp

%description
Poezio is a console-based client for XMPP, the protocol on which the
Jabber IM network is built. The network can be conneced to without
having to create an account and join various chatrooms immediately.
The client tries to look similar to the weechat/irssi IRC clients and
many commands are identical. Configuration can be done in a
configuration file or directly from the client.

%package doc
Summary:        Documentation for poezio
Group:          Productivity/Networking/Other
BuildArch:      noarch

%description doc
Documentation generated by the poezio package, but split out due to size.

%prep
%setup -q -n %{name}-v%{version}
%patch0 -p1

%build
%python3_build

%install
%python3_install
install -m 0755 -d %{buildroot}%{_docdir}/%{name}
mv %{buildroot}%{_docdir}/../%{name} %{buildroot}%{_docdir}/
install -m 0755 -d %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/io.poez.Poezio.svg
install -m 0644 data/poezio_logo.svg %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/io.poez.Poezio.svg
%fdupes %{buildroot}%{_libdir}/python3*/site-packages
%fdupes %{buildroot}%{_docdir}/%{name}

%files doc
%doc README.rst
%{_docdir}/poezio

%files
%license COPYING
%{_libdir}/python3*/site-packages/%{name}*
%{_bindir}/poezio*
%{_datadir}/poezio
%{_mandir}/man1/%{name}*%{ext_man}
%{_datadir}/applications/io.poez.Poezio.desktop
%{_datadir}/metainfo/io.poez.Poezio.appdata.xml
%{_datadir}/icons/hicolor/scalable/apps/io.poez.Poezio.svg

%changelog
