.TH zfcp_disk_configure "8" "February 2013" "s390-tools"
.SH NAME
zfcp_disk_configure \- Configures or deconfigures a SCSI over zFCP disk (LUN).
.SH SYNOPSIS
.B zfcp_disk_configure ccwid wwpn lun online
.SH DESCRIPTION
.B zfcp_disk_configure
is intended to make it easy to persistently add and remove SCSI over zFCP disks. In addition to bringing the disk online or offline, it will also create or delete the necessary udev rules for the disk.
.SH PARAMETERS
.IP ccwid
The device number of the zFCP adapter. Takes the form x.y.ssss where
.RS
.B x
is always 0 until IBM creates something that uses that number.
.RE
.RS
.B y
is the logical channel subsystem (lcss) number. Most often this is 0, but it could be non-zero.
.RE
.RS
.B ssss
is the four digit subchannel address of the device, in hexidecimal, with leading zeros. If entered in upper/mixed case, this is automatically converted to lower case.
.RE
.IP wwpn
Is the World Wide Port Number of the storage array in which the LUN resides. This will be a 16 digit hexidecimal number of the form 0x0123456789abcdef. You must obtain this number from the administrator of the storage array.
.IP lun
Is the Logical Unit Number of the specific disk in the storage array. This will also be a 16 digit hexidecimal number of the form 0x0123456789abcdef. You must obtain this number from the administrator of the storage array. Be careful in that some storage array administrator interfaces disply the LUN in decimal, and must be converted to hexidecimal to be used in this command.
.IP online
Either a literal 1 to bring the adapter online or a literal 0 to take it offline
.SH FILES
.I /etc/udev/rules.d/51-zfcp-<ccwid>.rules
.RS
This file provides the udev rules necessary to activate a specific zFCP adapter and the LUNs associated with it. Rules relating to the zFCP adapter are added by the zfcp_host_configure(8) script.
.RE
.SH ENVIRONMENT
.IP DEBUG
If set to "yes" some minimal debugging information is output during execution.
.SH DIAGNOSTICS
The following messages may be issued on stdout:
.IP
.B /sysfs not present
.RS
The sysfs file system could not be found in /proc/mounts, so there's nothing the script can do. Return code 1 is set.
.RE
.IP
.B No CCW device specified
.RS
This message should never be seen, since the script checks to make sure there are exactly four parameters specified. I.e., it is a sanity check. If it is seen, please open a bug report. Return code 1 is set.
.RE
.IP
.B Invalid device status ${ONLINE}
.RS
A value other than 0 or 1 was specified for the second parameter, online. Return code 2 is set.
.RE
.IP
.B No device ${CCW_CHAN_ID}
.RS
If a non-existent <ccwid> was specified for the first parameter. Remember the x.y.ssss format is necessary. Return code 3 is set.
.RE
.IP
.B WWPN ${FCP_WWPN} invalid
.RS
Activation of the WWPN failed. Return code 4 is set.
.RE
.IP
.B WWPN ${FCP_WWPN} for adapter ${CCW_CHAN_ID} not found
.RS
The WWPN specified isn't being "seen" by the zFCP adapter. This could have a number of different causes, such as an incorrect configuration on the storage array or SAN switch, a typographical error entering this command, etc. Return code 5 is set.
.RE
.IP
.B Could not activate FCP disk ${FCP_WWPN}:${FCP_LUN}
.RS
An attempt was made to activate the specified LUN, which failed. Return code 6 is set.
.RE
.IP
.B Could not deactivate SCSI disk ${_zfcp_scsi_id}
.RS
An attempt was made to deactivate the specified LUN, which failed. Return code 7 is set.
.RE
.IP
.B Could not deregister FCP LUN ${FCP_LUN}
.RS
An attempt was made to remove the specified LUN from the zFCP adapter, which failed. Return code 8 is set.
.RE

If environment variable DEBUG is set to "yes," the following messages may be issued on stdout:
.IP
.B No configuration file for adapter ${CCW_CHAN_ID}
.RS
The /etc/udev/rules.d/51-zfcp-<ccwid>.rules file does not exist. No return code is set, and execution continues.
.RE
.IP
.B FCP disk ${FCP_WWPN}:${FCP_LUN} already configured
.RS
The parameters specified activating the LUN, but it was already activated. Return code 0 is set.
.RE
.IP
.B FCP disk ${FCP_WWPN}:${FCP_LUN} does not exist
.RS
The parameters specified deactivating the LUN, but it is not currently activated. Return code 0 is set.
.RE
.IP
.B Configuring FCP disk ${FCP_WWPN}:${FCP_LUN}
.RS
Just a little bit of verbosity, since it just indicates that we got past certain error checks and will now try to do something useful.
.RE
.IP
.B ERP failed on FCP disk ${FCP_WWPN}:${FCP_LUN}
.RS
An attempt to bring the specified LUN online succeeded, but the device is marked as "failed" by the SCSI layer. Return code 7 is set.
.RE
.IP
.B Deconfiguring FCP disk ${FCP_WWPN}:${FCP_LUN}
.RS
Another bit of verbosity, which also just indicates that we got past certain error checks and will now try to do something useful.
.RE
.IP
.B No SCSI disk found for FCP disk ${FCP_WWPN}:${FCP_LUN}
.RS
This indicates that deactivating a SCSI disk was successful.
.RE
.SH BUGS
Gotta be some, I'm sure. If you find one, please open a bug report.
.SH SEE ALSO
zfcp_host_configure(8), zfcp_san_disc(8)
