.00;                       # finish .ig

'di           \" finish diversion--previous line must be blank
.nr nl 0-1    \" fake up transition to first page again
.nr % 0         \" start at page 1
'; __END__ ##### From here on it's a standard manual page - VERSION #####
.TH LaTeX2HTML 1
.AT 3
.SH NAME
latex2html \- translate LaTeX files to HTML (HyperText Markup Language)
.SH SYNOPSIS
.B

latex2html
   [-address author-address]
   [-antialias]
   [-antialias_text]
   [-ascii_mode]
   [-auto_navigation]
   [-auto_prefix]
   [-biblio URL]
   [-bottom_navigation]
   [-contents URL]
   [-contents_in_navigation]
   [-custom_titles]
   [-debug]
   [-dir output-directory]
   [-discard]
   [-down_title string]
   [-down_url URL]
   [-external_file filename]
   [-external_images]
   [-font_size size]
   [-h(elp)]
   [-html_version (2.0|3.0|3.2)[,(math|i18n|table)]*]
   [-images_only]
   [-index URL]
   [-index_in_navigation]
   [-info string]
   [-init_file file]
   [-iso_language type]
   [-ldump]
   [-link num]
   [-local_icons]
   [-long_titles num]
   [-next_page_in_navigation]
   [-no_antialias]
   [-no_antialias_text]
   [-no_auto_link]
   [-no_footnode]
   [-no_fork]
   [-no_images]
   [-no_math]
   [-no_navigation]
   [-no_reuse]
   [-no_subdir]
   [-no_tex_defs]
   [-no_white]
   [-nolatex]
   [-numbered_footnotes]
   [-prefix filename-prefix]
   [-prev_title string]
   [-prev_url URL]
   [-previous_page_in_navigation]
   [-ps_images]
   [-reuse reuse_option]
   [-scalable_fonts]
   [-short_extn]
   [-short_index]
   [-show_section_numbers]
   [-split + num]
   [-split num]
   [-t top-page-title]
   [-tmp path]
   [-toc_depth num]
   [-toc_stars]
   [-top_navigation]
   [-unsegment]
   [-up_title string]
   [-up_url URL]
   [-v]
   [-verbosity num]
   [-white]
   file(s)


.SH DESCRIPTION
.I LaTeX2HTML
is a Perl program that translates LaTeX source files into HTML. For each source
file given as an argument the translator will create a directory containing the
corresponding HTML files.
See the WWW online documentation or the /usr/share/doc/packages/latex2html/manual.ps.gz
file for more detailed information and examples.

.SH PROBLEMS
For information on various problems and remedies see the WWW online documentation
or the documents available in the distribution.
A mailing list for technical discussion about latex2html, bugs and enhancements is available at
latex2html@tug.org

.SH SUSE installation

In /usr/share/doc/packages/latex2html you may find more information about this package.

.SH AUTHOR
Nikos Drakos,  Computer Based Learning Unit, University of Leeds
<nikos@cbl.leeds.ac.uk>. Several people have contributed suggestions,
ideas, solutions, support and
encouragement.

The pstogif script uses the pstoppm.ps
postscript program originally written by Phillip Conrad (Perfect Byte, Inc.)
and modified by L.  Peter Deutsch (Aladdin Enterprises).

