#Type   Path                        Mode  User  Group   Age     Argument
d       /var/cache/shibboleth       0755  shibd  shibd    -       -
d       /var/log/shibboleth         0750  shibd  shibd    -       -