# See tmpfiles.d(5) for details

# Type	Path			Mode UID	GID  	Age Argument
d	/var/lib/nfs 		0755 root	root	-   -
d	/var/lib/nfs/sm		0700 statd	statd	-   -
d	/var/lib/nfs/sm.bak	0700 statd	statd	-   -
f	/var/lib/nfs/state	0644 root	root	-   -
d	/var/lib/nfs/rpc_pipefs	0755 root 	root 	-   -
d	/var/lib/nfs/v4recovery	0755 root	root	-   -
f	/var/lib/nfs/etab	0644 root	root	-   -
f	/var/lib/nfs/rmtab	0644 root	root	-   -
