.TH MIC "1" "July 2012" "Melanox imgen 1.0" "User Commands"
.SH NAME
mic \- InfiniScale-III EEPROM management/burning tool
.SH SYNOPSIS
.B mic
[\fIOPTIONS\fR]...
.SH DESCRIPTION
.\" Add any additional description here
.PP
.TP
\fB\-help\fR
print short usage message and exit
.TP
\fB\-nowarn\fR
do not print some warnings
.TP
\fB\-nofs\fR
the resulting image will not be failsafe
.TP
\fB\-version\fR
print version number
.TP
\fB\-dev_type\fR \fIDEVICE_TYPE\fR
the device for which the image is generated. Supported devices are MT47396,
MT23108, MT25208, MT25218, MT24204 or MT25204.
.TP
\fB\-fw\fR \fIFW_IMAGE_FILE\fR
specify the input file with the firmware
.TP
\fB\-conf\fR \fICONFIG_FILE\fR
read configuration (.INI) file
.TP
\fB\-wrconf\fR
write configuration (.INI) file
.TP
\fB\-wrimage\fR \fIEEPROM_IMAGE\fR
write the resulting image to a file with the given name
.TP
\fB\-format\fR \fIEEPROM_IMAGE_FMT\fR
outbut in the specified format. Format may be \fBIMAGE\fR, \fBDWORDS\fR or
\fBBINARY\fR. Default is \fBIMAGE\fR
.TP
\fB\-exp_rom\fR \fIEXP_ROM_FILE\fR
integrate the given extention file (in .img or .bin format) with the firmware
image (HCA's only)
.TP
\fB\-GROUP.PARAM \fR\fIVALUE\fR
set the specified parameter to VALUE
