.TH T2A "1" "July 2012" "Imgen 1.0" "User Commands"
.SH NAME
t2a \- Convert files from old MLX format to Mimage format
.SH SYNOPSIS
.B t2a
\fIDEVTYPE\fR \fIOLD\-MLX\-FILE\fR [\fIOUTPUT\-XML\-FILE\fR]
.br
.SH DESCRIPTION
.\" Add any additional description here
.PP
Converts files from old MLX format to Mimage format.
.TP
\fBDEVTYPE\fR
Allowed types are MT23108, MT25208, MT25218, MT24204or MT25204.
.TP
