# needssslcertforbuild

[Include]
Include=mkosi-obs

[Distribution]
Distribution=opensuse
Release=tumbleweed

[Output]
OutputDirectory=mkosi.output
Format=none
ImageVersion=0.0
SplitArtifacts=

[Content]
Bootable=false
Packages=
	aaa_base
	bash
	busybox-adduser
	busybox-bind-utils
	ca-certificates
	ca-certificates-mozilla
	coreutils
	coreutils-systemd
	efibootmgr
	glibc
	glibc-locale-base
	gpg2
	gptfdisk
	iproute2
	iputils
	kernel-default
	kernel-firmware-amdgpu
	kernel-firmware-network
	kernel-firmware-usb-network
	less
	libnss_usrfiles2
	libseccomp2
	login_defs
	mdadm
	openssh
	openSUSE-build-key
	openSUSE-release
	openSUSE-release-appliance-custom
	parted
	patterns-base-hardware
	procps
	systemd
	systemd-networkd
	systemd-presets-branding-openSUSE
	systemd-resolved
	tar
	timezone
	udev
	vim-small
	wget
	rdi-installer
	rdi-installer-utilities
	rdii-helper
	shim
	systemd-boot
	update-bootloader
