#
# spec file for package massif-visualizer
#
# Copyright (c) 2024 SUSE LLC
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Please submit bugfixes or comments via https://bugs.opensuse.org/
#


%define kf6_version 6.3.0
%define qt6_version 6.6.0

%bcond_without released
Name:           massif-visualizer
Version:        24.08.3
Release:        0
Summary:        Visualizer for output generated by Valgrind's massif tool
License:        LGPL-2.0-only
URL:            https://apps.kde.org/massif-visualizer
Source0:        https://download.kde.org/stable/release-service/%{version}/src/%{name}-%{version}.tar.xz
%if %{with released}
Source1:        https://download.kde.org/stable/release-service/%{version}/src/%{name}-%{version}.tar.xz.sig
Source2:        applications.keyring
%endif
BuildRequires:  kf6-extra-cmake-modules >= %{kf6_version}
BuildRequires:  shared-mime-info
BuildRequires:  update-desktop-files
BuildRequires:  cmake(KChart6) >= 3.0.0
BuildRequires:  cmake(KF6Archive) >= %{kf6_version}
BuildRequires:  cmake(KF6Config) >= %{kf6_version}
BuildRequires:  cmake(KF6CoreAddons) >= %{kf6_version}
BuildRequires:  cmake(KF6I18n) >= %{kf6_version}
BuildRequires:  cmake(KF6KIO) >= %{kf6_version}
BuildRequires:  cmake(KF6Parts) >= %{kf6_version}
BuildRequires:  cmake(KGraphViewerPart) >= 2.5.0
BuildRequires:  cmake(Qt6Core) >= %{qt6_version}
BuildRequires:  cmake(Qt6Core5Compat) >= %{qt6_version}
BuildRequires:  cmake(Qt6PrintSupport) >= %{qt6_version}
BuildRequires:  cmake(Qt6Svg) >= %{qt6_version}
BuildRequires:  cmake(Qt6Test) >= %{qt6_version}
BuildRequires:  cmake(Qt6Widgets) >= %{qt6_version}
Requires:       kgraphviewer >= 2.5.0
Recommends:     valgrind

%description
Massif Visualizer is a tool that visualizes massif data.
You run your application in Valgrind with --tool=massif and then open the
generated massif.out.pid file in the visualizer.
Gzip or Bzip2 compressed massif files can also be opened transparently.

%lang_package

%prep
%autosetup -p1

%build
%cmake_kf6

%kf6_build

%install
%kf6_install

%suse_update_desktop_file org.kde.massif-visualizer Debugger

%find_lang massif-visualizer %{name}.lang

%files lang -f %{name}.lang

%files
%license COPYING
%doc AUTHORS README
%{_kf6_applicationsdir}/org.kde.massif-visualizer.desktop
%{_kf6_appstreamdir}/org.kde.massif-visualizer.appdata.xml
%{_kf6_bindir}/massif-visualizer
%{_kf6_configkcfgdir}/massif-visualizer-settings.kcfg
%{_kf6_iconsdir}/hicolor/scalable/apps/massif-visualizer.svg
%{_kf6_sharedir}/massif-visualizer/
%{_kf6_sharedir}/mime/packages/massif.xml

%changelog
