# delete cache recursively when --boot is provided
# workaround for bnc#904620#c8 / lp#1392042
# "apparmor_parser --purge-cache" used for now, until a tmpfiles_remove rpm
# spec macro is available.
#R! /var/cache/apparmor/*

# for apparmor-utils
d /var/log/apparmor 0755 root root

# for apparmor-parser
d /var/cache/apparmor 0700 root root
L /etc/apparmor.d/cache.d - - - - /var/cache/apparmor
