.TH json_reformat 1
.SH NAME
json_reformat \- Reformat json from stdin
.SH SYNOPSIS
.B json_reformat
[
.I OPTION
]
.SH "DESCRIPTION"
A sample program to demonstrate the use of yajl.  json_reformat reformats json from stdin.
.SH OPTIONS
.TP
.B \-m
minimize json rather than beautify (default)
.TP
.B \-u
allow invalid UTF8 inside strings during parsing
.BR
.SH AUTHORS
     Lloyd Hilaiel <lloyd@hilaiel.com>


